// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/equip_lottery_client.proto

package app.protobuf.client;

public final class EquipLotteryClientContent {
  private EquipLotteryClientContent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EquipLotteryModuleObjClientProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.EquipLotteryModuleObjClientProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 dailyLotteryTimes = 1;</code>
     */
    boolean hasDailyLotteryTimes();
    /**
     * <code>optional int32 dailyLotteryTimes = 1;</code>
     */
    int getDailyLotteryTimes();

    /**
     * <code>optional int32 totalLotteryTimes = 2;</code>
     *
     * <pre>
     *客户端自己算出再买N次必定获得,杂项表equip_lottery_must_hit_required_times
     * </pre>
     */
    boolean hasTotalLotteryTimes();
    /**
     * <code>optional int32 totalLotteryTimes = 2;</code>
     *
     * <pre>
     *客户端自己算出再买N次必定获得,杂项表equip_lottery_must_hit_required_times
     * </pre>
     */
    int getTotalLotteryTimes();

    /**
     * <code>repeated int32 selfGoodsIdLog = 3;</code>
     *
     * <pre>
     *记录自己的获得极品的物品ID
     * </pre>
     */
    java.util.List<java.lang.Integer> getSelfGoodsIdLogList();
    /**
     * <code>repeated int32 selfGoodsIdLog = 3;</code>
     *
     * <pre>
     *记录自己的获得极品的物品ID
     * </pre>
     */
    int getSelfGoodsIdLogCount();
    /**
     * <code>repeated int32 selfGoodsIdLog = 3;</code>
     *
     * <pre>
     *记录自己的获得极品的物品ID
     * </pre>
     */
    int getSelfGoodsIdLog(int index);
  }
  /**
   * Protobuf type {@code proto.EquipLotteryModuleObjClientProto}
   *
   * <pre>
   * </pre>
   */
  public static final class EquipLotteryModuleObjClientProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.EquipLotteryModuleObjClientProto)
      EquipLotteryModuleObjClientProtoOrBuilder {
    // Use EquipLotteryModuleObjClientProto.newBuilder() to construct.
    private EquipLotteryModuleObjClientProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EquipLotteryModuleObjClientProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EquipLotteryModuleObjClientProto defaultInstance;
    public static EquipLotteryModuleObjClientProto getDefaultInstance() {
      return defaultInstance;
    }

    public EquipLotteryModuleObjClientProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EquipLotteryModuleObjClientProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              dailyLotteryTimes_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              totalLotteryTimes_ = input.readInt32();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                selfGoodsIdLog_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              selfGoodsIdLog_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                selfGoodsIdLog_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                selfGoodsIdLog_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          selfGoodsIdLog_ = java.util.Collections.unmodifiableList(selfGoodsIdLog_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return app.protobuf.client.EquipLotteryClientContent.internal_static_proto_EquipLotteryModuleObjClientProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return app.protobuf.client.EquipLotteryClientContent.internal_static_proto_EquipLotteryModuleObjClientProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto.class, app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto.Builder.class);
    }

    public static com.google.protobuf.Parser<EquipLotteryModuleObjClientProto> PARSER =
        new com.google.protobuf.AbstractParser<EquipLotteryModuleObjClientProto>() {
      public EquipLotteryModuleObjClientProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EquipLotteryModuleObjClientProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EquipLotteryModuleObjClientProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DAILYLOTTERYTIMES_FIELD_NUMBER = 1;
    private int dailyLotteryTimes_;
    /**
     * <code>optional int32 dailyLotteryTimes = 1;</code>
     */
    public boolean hasDailyLotteryTimes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 dailyLotteryTimes = 1;</code>
     */
    public int getDailyLotteryTimes() {
      return dailyLotteryTimes_;
    }

    public static final int TOTALLOTTERYTIMES_FIELD_NUMBER = 2;
    private int totalLotteryTimes_;
    /**
     * <code>optional int32 totalLotteryTimes = 2;</code>
     *
     * <pre>
     *客户端自己算出再买N次必定获得,杂项表equip_lottery_must_hit_required_times
     * </pre>
     */
    public boolean hasTotalLotteryTimes() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 totalLotteryTimes = 2;</code>
     *
     * <pre>
     *客户端自己算出再买N次必定获得,杂项表equip_lottery_must_hit_required_times
     * </pre>
     */
    public int getTotalLotteryTimes() {
      return totalLotteryTimes_;
    }

    public static final int SELFGOODSIDLOG_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> selfGoodsIdLog_;
    /**
     * <code>repeated int32 selfGoodsIdLog = 3;</code>
     *
     * <pre>
     *记录自己的获得极品的物品ID
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getSelfGoodsIdLogList() {
      return selfGoodsIdLog_;
    }
    /**
     * <code>repeated int32 selfGoodsIdLog = 3;</code>
     *
     * <pre>
     *记录自己的获得极品的物品ID
     * </pre>
     */
    public int getSelfGoodsIdLogCount() {
      return selfGoodsIdLog_.size();
    }
    /**
     * <code>repeated int32 selfGoodsIdLog = 3;</code>
     *
     * <pre>
     *记录自己的获得极品的物品ID
     * </pre>
     */
    public int getSelfGoodsIdLog(int index) {
      return selfGoodsIdLog_.get(index);
    }

    private void initFields() {
      dailyLotteryTimes_ = 0;
      totalLotteryTimes_ = 0;
      selfGoodsIdLog_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, dailyLotteryTimes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, totalLotteryTimes_);
      }
      for (int i = 0; i < selfGoodsIdLog_.size(); i++) {
        output.writeInt32(3, selfGoodsIdLog_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, dailyLotteryTimes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, totalLotteryTimes_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < selfGoodsIdLog_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(selfGoodsIdLog_.get(i));
        }
        size += dataSize;
        size += 1 * getSelfGoodsIdLogList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.EquipLotteryModuleObjClientProto}
     *
     * <pre>
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.EquipLotteryModuleObjClientProto)
        app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return app.protobuf.client.EquipLotteryClientContent.internal_static_proto_EquipLotteryModuleObjClientProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return app.protobuf.client.EquipLotteryClientContent.internal_static_proto_EquipLotteryModuleObjClientProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto.class, app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto.Builder.class);
      }

      // Construct using app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        dailyLotteryTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        totalLotteryTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        selfGoodsIdLog_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return app.protobuf.client.EquipLotteryClientContent.internal_static_proto_EquipLotteryModuleObjClientProto_descriptor;
      }

      public app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto getDefaultInstanceForType() {
        return app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto.getDefaultInstance();
      }

      public app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto build() {
        app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto buildPartial() {
        app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto result = new app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dailyLotteryTimes_ = dailyLotteryTimes_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.totalLotteryTimes_ = totalLotteryTimes_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          selfGoodsIdLog_ = java.util.Collections.unmodifiableList(selfGoodsIdLog_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.selfGoodsIdLog_ = selfGoodsIdLog_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto) {
          return mergeFrom((app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto other) {
        if (other == app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto.getDefaultInstance()) return this;
        if (other.hasDailyLotteryTimes()) {
          setDailyLotteryTimes(other.getDailyLotteryTimes());
        }
        if (other.hasTotalLotteryTimes()) {
          setTotalLotteryTimes(other.getTotalLotteryTimes());
        }
        if (!other.selfGoodsIdLog_.isEmpty()) {
          if (selfGoodsIdLog_.isEmpty()) {
            selfGoodsIdLog_ = other.selfGoodsIdLog_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSelfGoodsIdLogIsMutable();
            selfGoodsIdLog_.addAll(other.selfGoodsIdLog_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (app.protobuf.client.EquipLotteryClientContent.EquipLotteryModuleObjClientProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int dailyLotteryTimes_ ;
      /**
       * <code>optional int32 dailyLotteryTimes = 1;</code>
       */
      public boolean hasDailyLotteryTimes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 dailyLotteryTimes = 1;</code>
       */
      public int getDailyLotteryTimes() {
        return dailyLotteryTimes_;
      }
      /**
       * <code>optional int32 dailyLotteryTimes = 1;</code>
       */
      public Builder setDailyLotteryTimes(int value) {
        bitField0_ |= 0x00000001;
        dailyLotteryTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 dailyLotteryTimes = 1;</code>
       */
      public Builder clearDailyLotteryTimes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dailyLotteryTimes_ = 0;
        onChanged();
        return this;
      }

      private int totalLotteryTimes_ ;
      /**
       * <code>optional int32 totalLotteryTimes = 2;</code>
       *
       * <pre>
       *客户端自己算出再买N次必定获得,杂项表equip_lottery_must_hit_required_times
       * </pre>
       */
      public boolean hasTotalLotteryTimes() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 totalLotteryTimes = 2;</code>
       *
       * <pre>
       *客户端自己算出再买N次必定获得,杂项表equip_lottery_must_hit_required_times
       * </pre>
       */
      public int getTotalLotteryTimes() {
        return totalLotteryTimes_;
      }
      /**
       * <code>optional int32 totalLotteryTimes = 2;</code>
       *
       * <pre>
       *客户端自己算出再买N次必定获得,杂项表equip_lottery_must_hit_required_times
       * </pre>
       */
      public Builder setTotalLotteryTimes(int value) {
        bitField0_ |= 0x00000002;
        totalLotteryTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 totalLotteryTimes = 2;</code>
       *
       * <pre>
       *客户端自己算出再买N次必定获得,杂项表equip_lottery_must_hit_required_times
       * </pre>
       */
      public Builder clearTotalLotteryTimes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        totalLotteryTimes_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> selfGoodsIdLog_ = java.util.Collections.emptyList();
      private void ensureSelfGoodsIdLogIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          selfGoodsIdLog_ = new java.util.ArrayList<java.lang.Integer>(selfGoodsIdLog_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 selfGoodsIdLog = 3;</code>
       *
       * <pre>
       *记录自己的获得极品的物品ID
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getSelfGoodsIdLogList() {
        return java.util.Collections.unmodifiableList(selfGoodsIdLog_);
      }
      /**
       * <code>repeated int32 selfGoodsIdLog = 3;</code>
       *
       * <pre>
       *记录自己的获得极品的物品ID
       * </pre>
       */
      public int getSelfGoodsIdLogCount() {
        return selfGoodsIdLog_.size();
      }
      /**
       * <code>repeated int32 selfGoodsIdLog = 3;</code>
       *
       * <pre>
       *记录自己的获得极品的物品ID
       * </pre>
       */
      public int getSelfGoodsIdLog(int index) {
        return selfGoodsIdLog_.get(index);
      }
      /**
       * <code>repeated int32 selfGoodsIdLog = 3;</code>
       *
       * <pre>
       *记录自己的获得极品的物品ID
       * </pre>
       */
      public Builder setSelfGoodsIdLog(
          int index, int value) {
        ensureSelfGoodsIdLogIsMutable();
        selfGoodsIdLog_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 selfGoodsIdLog = 3;</code>
       *
       * <pre>
       *记录自己的获得极品的物品ID
       * </pre>
       */
      public Builder addSelfGoodsIdLog(int value) {
        ensureSelfGoodsIdLogIsMutable();
        selfGoodsIdLog_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 selfGoodsIdLog = 3;</code>
       *
       * <pre>
       *记录自己的获得极品的物品ID
       * </pre>
       */
      public Builder addAllSelfGoodsIdLog(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSelfGoodsIdLogIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, selfGoodsIdLog_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 selfGoodsIdLog = 3;</code>
       *
       * <pre>
       *记录自己的获得极品的物品ID
       * </pre>
       */
      public Builder clearSelfGoodsIdLog() {
        selfGoodsIdLog_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.EquipLotteryModuleObjClientProto)
    }

    static {
      defaultInstance = new EquipLotteryModuleObjClientProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.EquipLotteryModuleObjClientProto)
  }

  public interface EquipLotteryLogProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.EquipLotteryLogProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string heroName = 1;</code>
     *
     * <pre>
     *获得者名字
     * </pre>
     */
    boolean hasHeroName();
    /**
     * <code>optional string heroName = 1;</code>
     *
     * <pre>
     *获得者名字
     * </pre>
     */
    java.lang.String getHeroName();
    /**
     * <code>optional string heroName = 1;</code>
     *
     * <pre>
     *获得者名字
     * </pre>
     */
    com.google.protobuf.ByteString
        getHeroNameBytes();

    /**
     * <code>optional int32 goodsId = 2;</code>
     *
     * <pre>
     *获得物品ID
     * </pre>
     */
    boolean hasGoodsId();
    /**
     * <code>optional int32 goodsId = 2;</code>
     *
     * <pre>
     *获得物品ID
     * </pre>
     */
    int getGoodsId();
  }
  /**
   * Protobuf type {@code proto.EquipLotteryLogProto}
   */
  public static final class EquipLotteryLogProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.EquipLotteryLogProto)
      EquipLotteryLogProtoOrBuilder {
    // Use EquipLotteryLogProto.newBuilder() to construct.
    private EquipLotteryLogProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EquipLotteryLogProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EquipLotteryLogProto defaultInstance;
    public static EquipLotteryLogProto getDefaultInstance() {
      return defaultInstance;
    }

    public EquipLotteryLogProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EquipLotteryLogProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              heroName_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              goodsId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return app.protobuf.client.EquipLotteryClientContent.internal_static_proto_EquipLotteryLogProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return app.protobuf.client.EquipLotteryClientContent.internal_static_proto_EquipLotteryLogProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto.class, app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto.Builder.class);
    }

    public static com.google.protobuf.Parser<EquipLotteryLogProto> PARSER =
        new com.google.protobuf.AbstractParser<EquipLotteryLogProto>() {
      public EquipLotteryLogProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EquipLotteryLogProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EquipLotteryLogProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HERONAME_FIELD_NUMBER = 1;
    private java.lang.Object heroName_;
    /**
     * <code>optional string heroName = 1;</code>
     *
     * <pre>
     *获得者名字
     * </pre>
     */
    public boolean hasHeroName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string heroName = 1;</code>
     *
     * <pre>
     *获得者名字
     * </pre>
     */
    public java.lang.String getHeroName() {
      java.lang.Object ref = heroName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          heroName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string heroName = 1;</code>
     *
     * <pre>
     *获得者名字
     * </pre>
     */
    public com.google.protobuf.ByteString
        getHeroNameBytes() {
      java.lang.Object ref = heroName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        heroName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GOODSID_FIELD_NUMBER = 2;
    private int goodsId_;
    /**
     * <code>optional int32 goodsId = 2;</code>
     *
     * <pre>
     *获得物品ID
     * </pre>
     */
    public boolean hasGoodsId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 goodsId = 2;</code>
     *
     * <pre>
     *获得物品ID
     * </pre>
     */
    public int getGoodsId() {
      return goodsId_;
    }

    private void initFields() {
      heroName_ = "";
      goodsId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHeroNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, goodsId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHeroNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, goodsId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.EquipLotteryLogProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.EquipLotteryLogProto)
        app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return app.protobuf.client.EquipLotteryClientContent.internal_static_proto_EquipLotteryLogProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return app.protobuf.client.EquipLotteryClientContent.internal_static_proto_EquipLotteryLogProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto.class, app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto.Builder.class);
      }

      // Construct using app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        heroName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        goodsId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return app.protobuf.client.EquipLotteryClientContent.internal_static_proto_EquipLotteryLogProto_descriptor;
      }

      public app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto getDefaultInstanceForType() {
        return app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto.getDefaultInstance();
      }

      public app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto build() {
        app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto buildPartial() {
        app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto result = new app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.heroName_ = heroName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.goodsId_ = goodsId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto) {
          return mergeFrom((app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto other) {
        if (other == app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto.getDefaultInstance()) return this;
        if (other.hasHeroName()) {
          bitField0_ |= 0x00000001;
          heroName_ = other.heroName_;
          onChanged();
        }
        if (other.hasGoodsId()) {
          setGoodsId(other.getGoodsId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (app.protobuf.client.EquipLotteryClientContent.EquipLotteryLogProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object heroName_ = "";
      /**
       * <code>optional string heroName = 1;</code>
       *
       * <pre>
       *获得者名字
       * </pre>
       */
      public boolean hasHeroName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string heroName = 1;</code>
       *
       * <pre>
       *获得者名字
       * </pre>
       */
      public java.lang.String getHeroName() {
        java.lang.Object ref = heroName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            heroName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string heroName = 1;</code>
       *
       * <pre>
       *获得者名字
       * </pre>
       */
      public com.google.protobuf.ByteString
          getHeroNameBytes() {
        java.lang.Object ref = heroName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          heroName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string heroName = 1;</code>
       *
       * <pre>
       *获得者名字
       * </pre>
       */
      public Builder setHeroName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        heroName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string heroName = 1;</code>
       *
       * <pre>
       *获得者名字
       * </pre>
       */
      public Builder clearHeroName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        heroName_ = getDefaultInstance().getHeroName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string heroName = 1;</code>
       *
       * <pre>
       *获得者名字
       * </pre>
       */
      public Builder setHeroNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        heroName_ = value;
        onChanged();
        return this;
      }

      private int goodsId_ ;
      /**
       * <code>optional int32 goodsId = 2;</code>
       *
       * <pre>
       *获得物品ID
       * </pre>
       */
      public boolean hasGoodsId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 goodsId = 2;</code>
       *
       * <pre>
       *获得物品ID
       * </pre>
       */
      public int getGoodsId() {
        return goodsId_;
      }
      /**
       * <code>optional int32 goodsId = 2;</code>
       *
       * <pre>
       *获得物品ID
       * </pre>
       */
      public Builder setGoodsId(int value) {
        bitField0_ |= 0x00000002;
        goodsId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 goodsId = 2;</code>
       *
       * <pre>
       *获得物品ID
       * </pre>
       */
      public Builder clearGoodsId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        goodsId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.EquipLotteryLogProto)
    }

    static {
      defaultInstance = new EquipLotteryLogProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.EquipLotteryLogProto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_EquipLotteryModuleObjClientProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_EquipLotteryModuleObjClientProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_EquipLotteryLogProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_EquipLotteryLogProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!client/equip_lottery_client.proto\022\005pro" +
      "to\"p\n EquipLotteryModuleObjClientProto\022\031" +
      "\n\021dailyLotteryTimes\030\001 \001(\005\022\031\n\021totalLotter" +
      "yTimes\030\002 \001(\005\022\026\n\016selfGoodsIdLog\030\003 \003(\005\"9\n\024" +
      "EquipLotteryLogProto\022\020\n\010heroName\030\001 \001(\t\022\017" +
      "\n\007goodsId\030\002 \001(\005B2\n\023app.protobuf.clientB\031" +
      "EquipLotteryClientContentH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_EquipLotteryModuleObjClientProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_EquipLotteryModuleObjClientProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_EquipLotteryModuleObjClientProto_descriptor,
        new java.lang.String[] { "DailyLotteryTimes", "TotalLotteryTimes", "SelfGoodsIdLog", });
    internal_static_proto_EquipLotteryLogProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_EquipLotteryLogProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_EquipLotteryLogProto_descriptor,
        new java.lang.String[] { "HeroName", "GoodsId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
