// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/rune_client.proto

package app.protobuf.client;

public final class RuneContent {
  private RuneContent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RuneGridProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.RuneGridProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 gridId = 1;</code>
     *
     * <pre>
     * 格子ID
     * </pre>
     */
    boolean hasGridId();
    /**
     * <code>optional int32 gridId = 1;</code>
     *
     * <pre>
     * 格子ID
     * </pre>
     */
    int getGridId();

    /**
     * <code>optional .proto.GoodsProto rune = 2;</code>
     *
     * <pre>
     *对应的符文
     * </pre>
     */
    boolean hasRune();
    /**
     * <code>optional .proto.GoodsProto rune = 2;</code>
     *
     * <pre>
     *对应的符文
     * </pre>
     */
    app.protobuf.client.GoodsContent.GoodsProto getRune();
    /**
     * <code>optional .proto.GoodsProto rune = 2;</code>
     *
     * <pre>
     *对应的符文
     * </pre>
     */
    app.protobuf.client.GoodsContent.GoodsProtoOrBuilder getRuneOrBuilder();
  }
  /**
   * Protobuf type {@code proto.RuneGridProto}
   *
   * <pre>
   *已经开启的格子
   * </pre>
   */
  public static final class RuneGridProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.RuneGridProto)
      RuneGridProtoOrBuilder {
    // Use RuneGridProto.newBuilder() to construct.
    private RuneGridProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RuneGridProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RuneGridProto defaultInstance;
    public static RuneGridProto getDefaultInstance() {
      return defaultInstance;
    }

    public RuneGridProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RuneGridProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              gridId_ = input.readInt32();
              break;
            }
            case 18: {
              app.protobuf.client.GoodsContent.GoodsProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = rune_.toBuilder();
              }
              rune_ = input.readMessage(app.protobuf.client.GoodsContent.GoodsProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rune_);
                rune_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return app.protobuf.client.RuneContent.internal_static_proto_RuneGridProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return app.protobuf.client.RuneContent.internal_static_proto_RuneGridProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              app.protobuf.client.RuneContent.RuneGridProto.class, app.protobuf.client.RuneContent.RuneGridProto.Builder.class);
    }

    public static com.google.protobuf.Parser<RuneGridProto> PARSER =
        new com.google.protobuf.AbstractParser<RuneGridProto>() {
      public RuneGridProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RuneGridProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RuneGridProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int GRIDID_FIELD_NUMBER = 1;
    private int gridId_;
    /**
     * <code>optional int32 gridId = 1;</code>
     *
     * <pre>
     * 格子ID
     * </pre>
     */
    public boolean hasGridId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 gridId = 1;</code>
     *
     * <pre>
     * 格子ID
     * </pre>
     */
    public int getGridId() {
      return gridId_;
    }

    public static final int RUNE_FIELD_NUMBER = 2;
    private app.protobuf.client.GoodsContent.GoodsProto rune_;
    /**
     * <code>optional .proto.GoodsProto rune = 2;</code>
     *
     * <pre>
     *对应的符文
     * </pre>
     */
    public boolean hasRune() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .proto.GoodsProto rune = 2;</code>
     *
     * <pre>
     *对应的符文
     * </pre>
     */
    public app.protobuf.client.GoodsContent.GoodsProto getRune() {
      return rune_;
    }
    /**
     * <code>optional .proto.GoodsProto rune = 2;</code>
     *
     * <pre>
     *对应的符文
     * </pre>
     */
    public app.protobuf.client.GoodsContent.GoodsProtoOrBuilder getRuneOrBuilder() {
      return rune_;
    }

    private void initFields() {
      gridId_ = 0;
      rune_ = app.protobuf.client.GoodsContent.GoodsProto.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, gridId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, rune_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, gridId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, rune_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static app.protobuf.client.RuneContent.RuneGridProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.client.RuneContent.RuneGridProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.client.RuneContent.RuneGridProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.client.RuneContent.RuneGridProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.client.RuneContent.RuneGridProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.client.RuneContent.RuneGridProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static app.protobuf.client.RuneContent.RuneGridProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static app.protobuf.client.RuneContent.RuneGridProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static app.protobuf.client.RuneContent.RuneGridProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.client.RuneContent.RuneGridProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(app.protobuf.client.RuneContent.RuneGridProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.RuneGridProto}
     *
     * <pre>
     *已经开启的格子
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.RuneGridProto)
        app.protobuf.client.RuneContent.RuneGridProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return app.protobuf.client.RuneContent.internal_static_proto_RuneGridProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return app.protobuf.client.RuneContent.internal_static_proto_RuneGridProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                app.protobuf.client.RuneContent.RuneGridProto.class, app.protobuf.client.RuneContent.RuneGridProto.Builder.class);
      }

      // Construct using app.protobuf.client.RuneContent.RuneGridProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRuneFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        gridId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (runeBuilder_ == null) {
          rune_ = app.protobuf.client.GoodsContent.GoodsProto.getDefaultInstance();
        } else {
          runeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return app.protobuf.client.RuneContent.internal_static_proto_RuneGridProto_descriptor;
      }

      public app.protobuf.client.RuneContent.RuneGridProto getDefaultInstanceForType() {
        return app.protobuf.client.RuneContent.RuneGridProto.getDefaultInstance();
      }

      public app.protobuf.client.RuneContent.RuneGridProto build() {
        app.protobuf.client.RuneContent.RuneGridProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public app.protobuf.client.RuneContent.RuneGridProto buildPartial() {
        app.protobuf.client.RuneContent.RuneGridProto result = new app.protobuf.client.RuneContent.RuneGridProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gridId_ = gridId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (runeBuilder_ == null) {
          result.rune_ = rune_;
        } else {
          result.rune_ = runeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof app.protobuf.client.RuneContent.RuneGridProto) {
          return mergeFrom((app.protobuf.client.RuneContent.RuneGridProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(app.protobuf.client.RuneContent.RuneGridProto other) {
        if (other == app.protobuf.client.RuneContent.RuneGridProto.getDefaultInstance()) return this;
        if (other.hasGridId()) {
          setGridId(other.getGridId());
        }
        if (other.hasRune()) {
          mergeRune(other.getRune());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        app.protobuf.client.RuneContent.RuneGridProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (app.protobuf.client.RuneContent.RuneGridProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int gridId_ ;
      /**
       * <code>optional int32 gridId = 1;</code>
       *
       * <pre>
       * 格子ID
       * </pre>
       */
      public boolean hasGridId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 gridId = 1;</code>
       *
       * <pre>
       * 格子ID
       * </pre>
       */
      public int getGridId() {
        return gridId_;
      }
      /**
       * <code>optional int32 gridId = 1;</code>
       *
       * <pre>
       * 格子ID
       * </pre>
       */
      public Builder setGridId(int value) {
        bitField0_ |= 0x00000001;
        gridId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 gridId = 1;</code>
       *
       * <pre>
       * 格子ID
       * </pre>
       */
      public Builder clearGridId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gridId_ = 0;
        onChanged();
        return this;
      }

      private app.protobuf.client.GoodsContent.GoodsProto rune_ = app.protobuf.client.GoodsContent.GoodsProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          app.protobuf.client.GoodsContent.GoodsProto, app.protobuf.client.GoodsContent.GoodsProto.Builder, app.protobuf.client.GoodsContent.GoodsProtoOrBuilder> runeBuilder_;
      /**
       * <code>optional .proto.GoodsProto rune = 2;</code>
       *
       * <pre>
       *对应的符文
       * </pre>
       */
      public boolean hasRune() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .proto.GoodsProto rune = 2;</code>
       *
       * <pre>
       *对应的符文
       * </pre>
       */
      public app.protobuf.client.GoodsContent.GoodsProto getRune() {
        if (runeBuilder_ == null) {
          return rune_;
        } else {
          return runeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.GoodsProto rune = 2;</code>
       *
       * <pre>
       *对应的符文
       * </pre>
       */
      public Builder setRune(app.protobuf.client.GoodsContent.GoodsProto value) {
        if (runeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rune_ = value;
          onChanged();
        } else {
          runeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.GoodsProto rune = 2;</code>
       *
       * <pre>
       *对应的符文
       * </pre>
       */
      public Builder setRune(
          app.protobuf.client.GoodsContent.GoodsProto.Builder builderForValue) {
        if (runeBuilder_ == null) {
          rune_ = builderForValue.build();
          onChanged();
        } else {
          runeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.GoodsProto rune = 2;</code>
       *
       * <pre>
       *对应的符文
       * </pre>
       */
      public Builder mergeRune(app.protobuf.client.GoodsContent.GoodsProto value) {
        if (runeBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              rune_ != app.protobuf.client.GoodsContent.GoodsProto.getDefaultInstance()) {
            rune_ =
              app.protobuf.client.GoodsContent.GoodsProto.newBuilder(rune_).mergeFrom(value).buildPartial();
          } else {
            rune_ = value;
          }
          onChanged();
        } else {
          runeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.GoodsProto rune = 2;</code>
       *
       * <pre>
       *对应的符文
       * </pre>
       */
      public Builder clearRune() {
        if (runeBuilder_ == null) {
          rune_ = app.protobuf.client.GoodsContent.GoodsProto.getDefaultInstance();
          onChanged();
        } else {
          runeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .proto.GoodsProto rune = 2;</code>
       *
       * <pre>
       *对应的符文
       * </pre>
       */
      public app.protobuf.client.GoodsContent.GoodsProto.Builder getRuneBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRuneFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.GoodsProto rune = 2;</code>
       *
       * <pre>
       *对应的符文
       * </pre>
       */
      public app.protobuf.client.GoodsContent.GoodsProtoOrBuilder getRuneOrBuilder() {
        if (runeBuilder_ != null) {
          return runeBuilder_.getMessageOrBuilder();
        } else {
          return rune_;
        }
      }
      /**
       * <code>optional .proto.GoodsProto rune = 2;</code>
       *
       * <pre>
       *对应的符文
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          app.protobuf.client.GoodsContent.GoodsProto, app.protobuf.client.GoodsContent.GoodsProto.Builder, app.protobuf.client.GoodsContent.GoodsProtoOrBuilder> 
          getRuneFieldBuilder() {
        if (runeBuilder_ == null) {
          runeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              app.protobuf.client.GoodsContent.GoodsProto, app.protobuf.client.GoodsContent.GoodsProto.Builder, app.protobuf.client.GoodsContent.GoodsProtoOrBuilder>(
                  getRune(),
                  getParentForChildren(),
                  isClean());
          rune_ = null;
        }
        return runeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.RuneGridProto)
    }

    static {
      defaultInstance = new RuneGridProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.RuneGridProto)
  }

  public interface RuneGridProtosOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.RuneGridProtos)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.RuneGridProto grids = 1;</code>
     */
    java.util.List<app.protobuf.client.RuneContent.RuneGridProto> 
        getGridsList();
    /**
     * <code>repeated .proto.RuneGridProto grids = 1;</code>
     */
    app.protobuf.client.RuneContent.RuneGridProto getGrids(int index);
    /**
     * <code>repeated .proto.RuneGridProto grids = 1;</code>
     */
    int getGridsCount();
    /**
     * <code>repeated .proto.RuneGridProto grids = 1;</code>
     */
    java.util.List<? extends app.protobuf.client.RuneContent.RuneGridProtoOrBuilder> 
        getGridsOrBuilderList();
    /**
     * <code>repeated .proto.RuneGridProto grids = 1;</code>
     */
    app.protobuf.client.RuneContent.RuneGridProtoOrBuilder getGridsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.RuneGridProtos}
   */
  public static final class RuneGridProtos extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.RuneGridProtos)
      RuneGridProtosOrBuilder {
    // Use RuneGridProtos.newBuilder() to construct.
    private RuneGridProtos(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RuneGridProtos(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RuneGridProtos defaultInstance;
    public static RuneGridProtos getDefaultInstance() {
      return defaultInstance;
    }

    public RuneGridProtos getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RuneGridProtos(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                grids_ = new java.util.ArrayList<app.protobuf.client.RuneContent.RuneGridProto>();
                mutable_bitField0_ |= 0x00000001;
              }
              grids_.add(input.readMessage(app.protobuf.client.RuneContent.RuneGridProto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          grids_ = java.util.Collections.unmodifiableList(grids_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return app.protobuf.client.RuneContent.internal_static_proto_RuneGridProtos_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return app.protobuf.client.RuneContent.internal_static_proto_RuneGridProtos_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              app.protobuf.client.RuneContent.RuneGridProtos.class, app.protobuf.client.RuneContent.RuneGridProtos.Builder.class);
    }

    public static com.google.protobuf.Parser<RuneGridProtos> PARSER =
        new com.google.protobuf.AbstractParser<RuneGridProtos>() {
      public RuneGridProtos parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RuneGridProtos(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RuneGridProtos> getParserForType() {
      return PARSER;
    }

    public static final int GRIDS_FIELD_NUMBER = 1;
    private java.util.List<app.protobuf.client.RuneContent.RuneGridProto> grids_;
    /**
     * <code>repeated .proto.RuneGridProto grids = 1;</code>
     */
    public java.util.List<app.protobuf.client.RuneContent.RuneGridProto> getGridsList() {
      return grids_;
    }
    /**
     * <code>repeated .proto.RuneGridProto grids = 1;</code>
     */
    public java.util.List<? extends app.protobuf.client.RuneContent.RuneGridProtoOrBuilder> 
        getGridsOrBuilderList() {
      return grids_;
    }
    /**
     * <code>repeated .proto.RuneGridProto grids = 1;</code>
     */
    public int getGridsCount() {
      return grids_.size();
    }
    /**
     * <code>repeated .proto.RuneGridProto grids = 1;</code>
     */
    public app.protobuf.client.RuneContent.RuneGridProto getGrids(int index) {
      return grids_.get(index);
    }
    /**
     * <code>repeated .proto.RuneGridProto grids = 1;</code>
     */
    public app.protobuf.client.RuneContent.RuneGridProtoOrBuilder getGridsOrBuilder(
        int index) {
      return grids_.get(index);
    }

    private void initFields() {
      grids_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < grids_.size(); i++) {
        output.writeMessage(1, grids_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < grids_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, grids_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static app.protobuf.client.RuneContent.RuneGridProtos parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.client.RuneContent.RuneGridProtos parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.client.RuneContent.RuneGridProtos parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.client.RuneContent.RuneGridProtos parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.client.RuneContent.RuneGridProtos parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.client.RuneContent.RuneGridProtos parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static app.protobuf.client.RuneContent.RuneGridProtos parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static app.protobuf.client.RuneContent.RuneGridProtos parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static app.protobuf.client.RuneContent.RuneGridProtos parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.client.RuneContent.RuneGridProtos parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(app.protobuf.client.RuneContent.RuneGridProtos prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.RuneGridProtos}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.RuneGridProtos)
        app.protobuf.client.RuneContent.RuneGridProtosOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return app.protobuf.client.RuneContent.internal_static_proto_RuneGridProtos_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return app.protobuf.client.RuneContent.internal_static_proto_RuneGridProtos_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                app.protobuf.client.RuneContent.RuneGridProtos.class, app.protobuf.client.RuneContent.RuneGridProtos.Builder.class);
      }

      // Construct using app.protobuf.client.RuneContent.RuneGridProtos.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGridsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (gridsBuilder_ == null) {
          grids_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          gridsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return app.protobuf.client.RuneContent.internal_static_proto_RuneGridProtos_descriptor;
      }

      public app.protobuf.client.RuneContent.RuneGridProtos getDefaultInstanceForType() {
        return app.protobuf.client.RuneContent.RuneGridProtos.getDefaultInstance();
      }

      public app.protobuf.client.RuneContent.RuneGridProtos build() {
        app.protobuf.client.RuneContent.RuneGridProtos result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public app.protobuf.client.RuneContent.RuneGridProtos buildPartial() {
        app.protobuf.client.RuneContent.RuneGridProtos result = new app.protobuf.client.RuneContent.RuneGridProtos(this);
        int from_bitField0_ = bitField0_;
        if (gridsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            grids_ = java.util.Collections.unmodifiableList(grids_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.grids_ = grids_;
        } else {
          result.grids_ = gridsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof app.protobuf.client.RuneContent.RuneGridProtos) {
          return mergeFrom((app.protobuf.client.RuneContent.RuneGridProtos)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(app.protobuf.client.RuneContent.RuneGridProtos other) {
        if (other == app.protobuf.client.RuneContent.RuneGridProtos.getDefaultInstance()) return this;
        if (gridsBuilder_ == null) {
          if (!other.grids_.isEmpty()) {
            if (grids_.isEmpty()) {
              grids_ = other.grids_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGridsIsMutable();
              grids_.addAll(other.grids_);
            }
            onChanged();
          }
        } else {
          if (!other.grids_.isEmpty()) {
            if (gridsBuilder_.isEmpty()) {
              gridsBuilder_.dispose();
              gridsBuilder_ = null;
              grids_ = other.grids_;
              bitField0_ = (bitField0_ & ~0x00000001);
              gridsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGridsFieldBuilder() : null;
            } else {
              gridsBuilder_.addAllMessages(other.grids_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        app.protobuf.client.RuneContent.RuneGridProtos parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (app.protobuf.client.RuneContent.RuneGridProtos) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<app.protobuf.client.RuneContent.RuneGridProto> grids_ =
        java.util.Collections.emptyList();
      private void ensureGridsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          grids_ = new java.util.ArrayList<app.protobuf.client.RuneContent.RuneGridProto>(grids_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          app.protobuf.client.RuneContent.RuneGridProto, app.protobuf.client.RuneContent.RuneGridProto.Builder, app.protobuf.client.RuneContent.RuneGridProtoOrBuilder> gridsBuilder_;

      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public java.util.List<app.protobuf.client.RuneContent.RuneGridProto> getGridsList() {
        if (gridsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(grids_);
        } else {
          return gridsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public int getGridsCount() {
        if (gridsBuilder_ == null) {
          return grids_.size();
        } else {
          return gridsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public app.protobuf.client.RuneContent.RuneGridProto getGrids(int index) {
        if (gridsBuilder_ == null) {
          return grids_.get(index);
        } else {
          return gridsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public Builder setGrids(
          int index, app.protobuf.client.RuneContent.RuneGridProto value) {
        if (gridsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGridsIsMutable();
          grids_.set(index, value);
          onChanged();
        } else {
          gridsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public Builder setGrids(
          int index, app.protobuf.client.RuneContent.RuneGridProto.Builder builderForValue) {
        if (gridsBuilder_ == null) {
          ensureGridsIsMutable();
          grids_.set(index, builderForValue.build());
          onChanged();
        } else {
          gridsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public Builder addGrids(app.protobuf.client.RuneContent.RuneGridProto value) {
        if (gridsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGridsIsMutable();
          grids_.add(value);
          onChanged();
        } else {
          gridsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public Builder addGrids(
          int index, app.protobuf.client.RuneContent.RuneGridProto value) {
        if (gridsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGridsIsMutable();
          grids_.add(index, value);
          onChanged();
        } else {
          gridsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public Builder addGrids(
          app.protobuf.client.RuneContent.RuneGridProto.Builder builderForValue) {
        if (gridsBuilder_ == null) {
          ensureGridsIsMutable();
          grids_.add(builderForValue.build());
          onChanged();
        } else {
          gridsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public Builder addGrids(
          int index, app.protobuf.client.RuneContent.RuneGridProto.Builder builderForValue) {
        if (gridsBuilder_ == null) {
          ensureGridsIsMutable();
          grids_.add(index, builderForValue.build());
          onChanged();
        } else {
          gridsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public Builder addAllGrids(
          java.lang.Iterable<? extends app.protobuf.client.RuneContent.RuneGridProto> values) {
        if (gridsBuilder_ == null) {
          ensureGridsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, grids_);
          onChanged();
        } else {
          gridsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public Builder clearGrids() {
        if (gridsBuilder_ == null) {
          grids_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          gridsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public Builder removeGrids(int index) {
        if (gridsBuilder_ == null) {
          ensureGridsIsMutable();
          grids_.remove(index);
          onChanged();
        } else {
          gridsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public app.protobuf.client.RuneContent.RuneGridProto.Builder getGridsBuilder(
          int index) {
        return getGridsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public app.protobuf.client.RuneContent.RuneGridProtoOrBuilder getGridsOrBuilder(
          int index) {
        if (gridsBuilder_ == null) {
          return grids_.get(index);  } else {
          return gridsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public java.util.List<? extends app.protobuf.client.RuneContent.RuneGridProtoOrBuilder> 
           getGridsOrBuilderList() {
        if (gridsBuilder_ != null) {
          return gridsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(grids_);
        }
      }
      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public app.protobuf.client.RuneContent.RuneGridProto.Builder addGridsBuilder() {
        return getGridsFieldBuilder().addBuilder(
            app.protobuf.client.RuneContent.RuneGridProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public app.protobuf.client.RuneContent.RuneGridProto.Builder addGridsBuilder(
          int index) {
        return getGridsFieldBuilder().addBuilder(
            index, app.protobuf.client.RuneContent.RuneGridProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.RuneGridProto grids = 1;</code>
       */
      public java.util.List<app.protobuf.client.RuneContent.RuneGridProto.Builder> 
           getGridsBuilderList() {
        return getGridsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          app.protobuf.client.RuneContent.RuneGridProto, app.protobuf.client.RuneContent.RuneGridProto.Builder, app.protobuf.client.RuneContent.RuneGridProtoOrBuilder> 
          getGridsFieldBuilder() {
        if (gridsBuilder_ == null) {
          gridsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              app.protobuf.client.RuneContent.RuneGridProto, app.protobuf.client.RuneContent.RuneGridProto.Builder, app.protobuf.client.RuneContent.RuneGridProtoOrBuilder>(
                  grids_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          grids_ = null;
        }
        return gridsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.RuneGridProtos)
    }

    static {
      defaultInstance = new RuneGridProtos(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.RuneGridProtos)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RuneGridProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_RuneGridProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RuneGridProtos_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_RuneGridProtos_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030client/rune_client.proto\022\005proto\032\022clien" +
      "t/goods.proto\"@\n\rRuneGridProto\022\016\n\006gridId" +
      "\030\001 \001(\005\022\037\n\004rune\030\002 \001(\0132\021.proto.GoodsProto\"" +
      "5\n\016RuneGridProtos\022#\n\005grids\030\001 \003(\0132\024.proto" +
      ".RuneGridProtoB$\n\023app.protobuf.clientB\013R" +
      "uneContentH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          app.protobuf.client.GoodsContent.getDescriptor(),
        }, assigner);
    internal_static_proto_RuneGridProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_RuneGridProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_RuneGridProto_descriptor,
        new java.lang.String[] { "GridId", "Rune", });
    internal_static_proto_RuneGridProtos_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_RuneGridProtos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_RuneGridProtos_descriptor,
        new java.lang.String[] { "Grids", });
    app.protobuf.client.GoodsContent.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
