// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/nickname_client.proto

package app.protobuf.client;

public final class NicknameClientContent {
  private NicknameClientContent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NicknameModuleObjClientProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.NicknameModuleObjClientProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
     *
     * <pre>
     *已经获得的称号
     * </pre>
     */
    java.util.List<app.protobuf.client.NicknameClientContent.NicknameClientProto> 
        getNicknameList();
    /**
     * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
     *
     * <pre>
     *已经获得的称号
     * </pre>
     */
    app.protobuf.client.NicknameClientContent.NicknameClientProto getNickname(int index);
    /**
     * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
     *
     * <pre>
     *已经获得的称号
     * </pre>
     */
    int getNicknameCount();
    /**
     * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
     *
     * <pre>
     *已经获得的称号
     * </pre>
     */
    java.util.List<? extends app.protobuf.client.NicknameClientContent.NicknameClientProtoOrBuilder> 
        getNicknameOrBuilderList();
    /**
     * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
     *
     * <pre>
     *已经获得的称号
     * </pre>
     */
    app.protobuf.client.NicknameClientContent.NicknameClientProtoOrBuilder getNicknameOrBuilder(
        int index);

    /**
     * <code>optional int32 use_id = 2;</code>
     *
     * <pre>
     *当前正在使用的称号
     * </pre>
     */
    boolean hasUseId();
    /**
     * <code>optional int32 use_id = 2;</code>
     *
     * <pre>
     *当前正在使用的称号
     * </pre>
     */
    int getUseId();
  }
  /**
   * Protobuf type {@code proto.NicknameModuleObjClientProto}
   *
   * <pre>
   * </pre>
   */
  public static final class NicknameModuleObjClientProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.NicknameModuleObjClientProto)
      NicknameModuleObjClientProtoOrBuilder {
    // Use NicknameModuleObjClientProto.newBuilder() to construct.
    private NicknameModuleObjClientProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NicknameModuleObjClientProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NicknameModuleObjClientProto defaultInstance;
    public static NicknameModuleObjClientProto getDefaultInstance() {
      return defaultInstance;
    }

    public NicknameModuleObjClientProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NicknameModuleObjClientProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                nickname_ = new java.util.ArrayList<app.protobuf.client.NicknameClientContent.NicknameClientProto>();
                mutable_bitField0_ |= 0x00000001;
              }
              nickname_.add(input.readMessage(app.protobuf.client.NicknameClientContent.NicknameClientProto.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              useId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          nickname_ = java.util.Collections.unmodifiableList(nickname_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return app.protobuf.client.NicknameClientContent.internal_static_proto_NicknameModuleObjClientProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return app.protobuf.client.NicknameClientContent.internal_static_proto_NicknameModuleObjClientProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto.class, app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto.Builder.class);
    }

    public static com.google.protobuf.Parser<NicknameModuleObjClientProto> PARSER =
        new com.google.protobuf.AbstractParser<NicknameModuleObjClientProto>() {
      public NicknameModuleObjClientProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NicknameModuleObjClientProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NicknameModuleObjClientProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NICKNAME_FIELD_NUMBER = 1;
    private java.util.List<app.protobuf.client.NicknameClientContent.NicknameClientProto> nickname_;
    /**
     * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
     *
     * <pre>
     *已经获得的称号
     * </pre>
     */
    public java.util.List<app.protobuf.client.NicknameClientContent.NicknameClientProto> getNicknameList() {
      return nickname_;
    }
    /**
     * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
     *
     * <pre>
     *已经获得的称号
     * </pre>
     */
    public java.util.List<? extends app.protobuf.client.NicknameClientContent.NicknameClientProtoOrBuilder> 
        getNicknameOrBuilderList() {
      return nickname_;
    }
    /**
     * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
     *
     * <pre>
     *已经获得的称号
     * </pre>
     */
    public int getNicknameCount() {
      return nickname_.size();
    }
    /**
     * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
     *
     * <pre>
     *已经获得的称号
     * </pre>
     */
    public app.protobuf.client.NicknameClientContent.NicknameClientProto getNickname(int index) {
      return nickname_.get(index);
    }
    /**
     * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
     *
     * <pre>
     *已经获得的称号
     * </pre>
     */
    public app.protobuf.client.NicknameClientContent.NicknameClientProtoOrBuilder getNicknameOrBuilder(
        int index) {
      return nickname_.get(index);
    }

    public static final int USE_ID_FIELD_NUMBER = 2;
    private int useId_;
    /**
     * <code>optional int32 use_id = 2;</code>
     *
     * <pre>
     *当前正在使用的称号
     * </pre>
     */
    public boolean hasUseId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 use_id = 2;</code>
     *
     * <pre>
     *当前正在使用的称号
     * </pre>
     */
    public int getUseId() {
      return useId_;
    }

    private void initFields() {
      nickname_ = java.util.Collections.emptyList();
      useId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getNicknameCount(); i++) {
        if (!getNickname(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < nickname_.size(); i++) {
        output.writeMessage(1, nickname_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, useId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < nickname_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, nickname_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, useId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.NicknameModuleObjClientProto}
     *
     * <pre>
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.NicknameModuleObjClientProto)
        app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return app.protobuf.client.NicknameClientContent.internal_static_proto_NicknameModuleObjClientProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return app.protobuf.client.NicknameClientContent.internal_static_proto_NicknameModuleObjClientProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto.class, app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto.Builder.class);
      }

      // Construct using app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNicknameFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (nicknameBuilder_ == null) {
          nickname_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nicknameBuilder_.clear();
        }
        useId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return app.protobuf.client.NicknameClientContent.internal_static_proto_NicknameModuleObjClientProto_descriptor;
      }

      public app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto getDefaultInstanceForType() {
        return app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto.getDefaultInstance();
      }

      public app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto build() {
        app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto buildPartial() {
        app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto result = new app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (nicknameBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            nickname_ = java.util.Collections.unmodifiableList(nickname_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nickname_ = nickname_;
        } else {
          result.nickname_ = nicknameBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.useId_ = useId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto) {
          return mergeFrom((app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto other) {
        if (other == app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto.getDefaultInstance()) return this;
        if (nicknameBuilder_ == null) {
          if (!other.nickname_.isEmpty()) {
            if (nickname_.isEmpty()) {
              nickname_ = other.nickname_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNicknameIsMutable();
              nickname_.addAll(other.nickname_);
            }
            onChanged();
          }
        } else {
          if (!other.nickname_.isEmpty()) {
            if (nicknameBuilder_.isEmpty()) {
              nicknameBuilder_.dispose();
              nicknameBuilder_ = null;
              nickname_ = other.nickname_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nicknameBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNicknameFieldBuilder() : null;
            } else {
              nicknameBuilder_.addAllMessages(other.nickname_);
            }
          }
        }
        if (other.hasUseId()) {
          setUseId(other.getUseId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getNicknameCount(); i++) {
          if (!getNickname(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (app.protobuf.client.NicknameClientContent.NicknameModuleObjClientProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<app.protobuf.client.NicknameClientContent.NicknameClientProto> nickname_ =
        java.util.Collections.emptyList();
      private void ensureNicknameIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          nickname_ = new java.util.ArrayList<app.protobuf.client.NicknameClientContent.NicknameClientProto>(nickname_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          app.protobuf.client.NicknameClientContent.NicknameClientProto, app.protobuf.client.NicknameClientContent.NicknameClientProto.Builder, app.protobuf.client.NicknameClientContent.NicknameClientProtoOrBuilder> nicknameBuilder_;

      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public java.util.List<app.protobuf.client.NicknameClientContent.NicknameClientProto> getNicknameList() {
        if (nicknameBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nickname_);
        } else {
          return nicknameBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public int getNicknameCount() {
        if (nicknameBuilder_ == null) {
          return nickname_.size();
        } else {
          return nicknameBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public app.protobuf.client.NicknameClientContent.NicknameClientProto getNickname(int index) {
        if (nicknameBuilder_ == null) {
          return nickname_.get(index);
        } else {
          return nicknameBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public Builder setNickname(
          int index, app.protobuf.client.NicknameClientContent.NicknameClientProto value) {
        if (nicknameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNicknameIsMutable();
          nickname_.set(index, value);
          onChanged();
        } else {
          nicknameBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public Builder setNickname(
          int index, app.protobuf.client.NicknameClientContent.NicknameClientProto.Builder builderForValue) {
        if (nicknameBuilder_ == null) {
          ensureNicknameIsMutable();
          nickname_.set(index, builderForValue.build());
          onChanged();
        } else {
          nicknameBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public Builder addNickname(app.protobuf.client.NicknameClientContent.NicknameClientProto value) {
        if (nicknameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNicknameIsMutable();
          nickname_.add(value);
          onChanged();
        } else {
          nicknameBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public Builder addNickname(
          int index, app.protobuf.client.NicknameClientContent.NicknameClientProto value) {
        if (nicknameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNicknameIsMutable();
          nickname_.add(index, value);
          onChanged();
        } else {
          nicknameBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public Builder addNickname(
          app.protobuf.client.NicknameClientContent.NicknameClientProto.Builder builderForValue) {
        if (nicknameBuilder_ == null) {
          ensureNicknameIsMutable();
          nickname_.add(builderForValue.build());
          onChanged();
        } else {
          nicknameBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public Builder addNickname(
          int index, app.protobuf.client.NicknameClientContent.NicknameClientProto.Builder builderForValue) {
        if (nicknameBuilder_ == null) {
          ensureNicknameIsMutable();
          nickname_.add(index, builderForValue.build());
          onChanged();
        } else {
          nicknameBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public Builder addAllNickname(
          java.lang.Iterable<? extends app.protobuf.client.NicknameClientContent.NicknameClientProto> values) {
        if (nicknameBuilder_ == null) {
          ensureNicknameIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nickname_);
          onChanged();
        } else {
          nicknameBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public Builder clearNickname() {
        if (nicknameBuilder_ == null) {
          nickname_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nicknameBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public Builder removeNickname(int index) {
        if (nicknameBuilder_ == null) {
          ensureNicknameIsMutable();
          nickname_.remove(index);
          onChanged();
        } else {
          nicknameBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public app.protobuf.client.NicknameClientContent.NicknameClientProto.Builder getNicknameBuilder(
          int index) {
        return getNicknameFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public app.protobuf.client.NicknameClientContent.NicknameClientProtoOrBuilder getNicknameOrBuilder(
          int index) {
        if (nicknameBuilder_ == null) {
          return nickname_.get(index);  } else {
          return nicknameBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public java.util.List<? extends app.protobuf.client.NicknameClientContent.NicknameClientProtoOrBuilder> 
           getNicknameOrBuilderList() {
        if (nicknameBuilder_ != null) {
          return nicknameBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nickname_);
        }
      }
      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public app.protobuf.client.NicknameClientContent.NicknameClientProto.Builder addNicknameBuilder() {
        return getNicknameFieldBuilder().addBuilder(
            app.protobuf.client.NicknameClientContent.NicknameClientProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public app.protobuf.client.NicknameClientContent.NicknameClientProto.Builder addNicknameBuilder(
          int index) {
        return getNicknameFieldBuilder().addBuilder(
            index, app.protobuf.client.NicknameClientContent.NicknameClientProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.NicknameClientProto nickname = 1;</code>
       *
       * <pre>
       *已经获得的称号
       * </pre>
       */
      public java.util.List<app.protobuf.client.NicknameClientContent.NicknameClientProto.Builder> 
           getNicknameBuilderList() {
        return getNicknameFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          app.protobuf.client.NicknameClientContent.NicknameClientProto, app.protobuf.client.NicknameClientContent.NicknameClientProto.Builder, app.protobuf.client.NicknameClientContent.NicknameClientProtoOrBuilder> 
          getNicknameFieldBuilder() {
        if (nicknameBuilder_ == null) {
          nicknameBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              app.protobuf.client.NicknameClientContent.NicknameClientProto, app.protobuf.client.NicknameClientContent.NicknameClientProto.Builder, app.protobuf.client.NicknameClientContent.NicknameClientProtoOrBuilder>(
                  nickname_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          nickname_ = null;
        }
        return nicknameBuilder_;
      }

      private int useId_ ;
      /**
       * <code>optional int32 use_id = 2;</code>
       *
       * <pre>
       *当前正在使用的称号
       * </pre>
       */
      public boolean hasUseId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 use_id = 2;</code>
       *
       * <pre>
       *当前正在使用的称号
       * </pre>
       */
      public int getUseId() {
        return useId_;
      }
      /**
       * <code>optional int32 use_id = 2;</code>
       *
       * <pre>
       *当前正在使用的称号
       * </pre>
       */
      public Builder setUseId(int value) {
        bitField0_ |= 0x00000002;
        useId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 use_id = 2;</code>
       *
       * <pre>
       *当前正在使用的称号
       * </pre>
       */
      public Builder clearUseId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        useId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.NicknameModuleObjClientProto)
    }

    static {
      defaultInstance = new NicknameModuleObjClientProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.NicknameModuleObjClientProto)
  }

  public interface NicknameClientProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.NicknameClientProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional int32 expired_time = 2;</code>
     *
     * <pre>
     *过期时间(秒) ，0为永久
     * </pre>
     */
    boolean hasExpiredTime();
    /**
     * <code>optional int32 expired_time = 2;</code>
     *
     * <pre>
     *过期时间(秒) ，0为永久
     * </pre>
     */
    int getExpiredTime();
  }
  /**
   * Protobuf type {@code proto.NicknameClientProto}
   */
  public static final class NicknameClientProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.NicknameClientProto)
      NicknameClientProtoOrBuilder {
    // Use NicknameClientProto.newBuilder() to construct.
    private NicknameClientProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NicknameClientProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NicknameClientProto defaultInstance;
    public static NicknameClientProto getDefaultInstance() {
      return defaultInstance;
    }

    public NicknameClientProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NicknameClientProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              expiredTime_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return app.protobuf.client.NicknameClientContent.internal_static_proto_NicknameClientProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return app.protobuf.client.NicknameClientContent.internal_static_proto_NicknameClientProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              app.protobuf.client.NicknameClientContent.NicknameClientProto.class, app.protobuf.client.NicknameClientContent.NicknameClientProto.Builder.class);
    }

    public static com.google.protobuf.Parser<NicknameClientProto> PARSER =
        new com.google.protobuf.AbstractParser<NicknameClientProto>() {
      public NicknameClientProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NicknameClientProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NicknameClientProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int EXPIRED_TIME_FIELD_NUMBER = 2;
    private int expiredTime_;
    /**
     * <code>optional int32 expired_time = 2;</code>
     *
     * <pre>
     *过期时间(秒) ，0为永久
     * </pre>
     */
    public boolean hasExpiredTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 expired_time = 2;</code>
     *
     * <pre>
     *过期时间(秒) ，0为永久
     * </pre>
     */
    public int getExpiredTime() {
      return expiredTime_;
    }

    private void initFields() {
      id_ = 0;
      expiredTime_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, expiredTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, expiredTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static app.protobuf.client.NicknameClientContent.NicknameClientProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameClientProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameClientProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameClientProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameClientProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameClientProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameClientProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameClientProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameClientProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.client.NicknameClientContent.NicknameClientProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(app.protobuf.client.NicknameClientContent.NicknameClientProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.NicknameClientProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.NicknameClientProto)
        app.protobuf.client.NicknameClientContent.NicknameClientProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return app.protobuf.client.NicknameClientContent.internal_static_proto_NicknameClientProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return app.protobuf.client.NicknameClientContent.internal_static_proto_NicknameClientProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                app.protobuf.client.NicknameClientContent.NicknameClientProto.class, app.protobuf.client.NicknameClientContent.NicknameClientProto.Builder.class);
      }

      // Construct using app.protobuf.client.NicknameClientContent.NicknameClientProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        expiredTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return app.protobuf.client.NicknameClientContent.internal_static_proto_NicknameClientProto_descriptor;
      }

      public app.protobuf.client.NicknameClientContent.NicknameClientProto getDefaultInstanceForType() {
        return app.protobuf.client.NicknameClientContent.NicknameClientProto.getDefaultInstance();
      }

      public app.protobuf.client.NicknameClientContent.NicknameClientProto build() {
        app.protobuf.client.NicknameClientContent.NicknameClientProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public app.protobuf.client.NicknameClientContent.NicknameClientProto buildPartial() {
        app.protobuf.client.NicknameClientContent.NicknameClientProto result = new app.protobuf.client.NicknameClientContent.NicknameClientProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.expiredTime_ = expiredTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof app.protobuf.client.NicknameClientContent.NicknameClientProto) {
          return mergeFrom((app.protobuf.client.NicknameClientContent.NicknameClientProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(app.protobuf.client.NicknameClientContent.NicknameClientProto other) {
        if (other == app.protobuf.client.NicknameClientContent.NicknameClientProto.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasExpiredTime()) {
          setExpiredTime(other.getExpiredTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        app.protobuf.client.NicknameClientContent.NicknameClientProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (app.protobuf.client.NicknameClientContent.NicknameClientProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int expiredTime_ ;
      /**
       * <code>optional int32 expired_time = 2;</code>
       *
       * <pre>
       *过期时间(秒) ，0为永久
       * </pre>
       */
      public boolean hasExpiredTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 expired_time = 2;</code>
       *
       * <pre>
       *过期时间(秒) ，0为永久
       * </pre>
       */
      public int getExpiredTime() {
        return expiredTime_;
      }
      /**
       * <code>optional int32 expired_time = 2;</code>
       *
       * <pre>
       *过期时间(秒) ，0为永久
       * </pre>
       */
      public Builder setExpiredTime(int value) {
        bitField0_ |= 0x00000002;
        expiredTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 expired_time = 2;</code>
       *
       * <pre>
       *过期时间(秒) ，0为永久
       * </pre>
       */
      public Builder clearExpiredTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        expiredTime_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.NicknameClientProto)
    }

    static {
      defaultInstance = new NicknameClientProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.NicknameClientProto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_NicknameModuleObjClientProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_NicknameModuleObjClientProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_NicknameClientProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_NicknameClientProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034client/nickname_client.proto\022\005proto\"\\\n" +
      "\034NicknameModuleObjClientProto\022,\n\010nicknam" +
      "e\030\001 \003(\0132\032.proto.NicknameClientProto\022\016\n\006u" +
      "se_id\030\002 \001(\005\"7\n\023NicknameClientProto\022\n\n\002id" +
      "\030\001 \002(\005\022\024\n\014expired_time\030\002 \001(\005B.\n\023app.prot" +
      "obuf.clientB\025NicknameClientContentH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_NicknameModuleObjClientProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_NicknameModuleObjClientProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_NicknameModuleObjClientProto_descriptor,
        new java.lang.String[] { "Nickname", "UseId", });
    internal_static_proto_NicknameClientProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_NicknameClientProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_NicknameClientProto_descriptor,
        new java.lang.String[] { "Id", "ExpiredTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
