// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/resource_back_client.proto

package app.protobuf.client;

public final class ResourceBackClientContent {
  private ResourceBackClientContent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResourceBackModuleObjClientProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ResourceBackModuleObjClientProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 updateRemainTimesLevel = 1;</code>
     *
     * <pre>
     *最后一次更新资源可找回次数时的等级，根据这个显示奖励
     * </pre>
     */
    boolean hasUpdateRemainTimesLevel();
    /**
     * <code>optional int32 updateRemainTimesLevel = 1;</code>
     *
     * <pre>
     *最后一次更新资源可找回次数时的等级，根据这个显示奖励
     * </pre>
     */
    int getUpdateRemainTimesLevel();

    /**
     * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
     */
    java.util.List<app.protobuf.client.ResourceBackClientContent.ResourceTypeObj> 
        getObjsList();
    /**
     * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
     */
    app.protobuf.client.ResourceBackClientContent.ResourceTypeObj getObjs(int index);
    /**
     * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
     */
    int getObjsCount();
    /**
     * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
     */
    java.util.List<? extends app.protobuf.client.ResourceBackClientContent.ResourceTypeObjOrBuilder> 
        getObjsOrBuilderList();
    /**
     * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
     */
    app.protobuf.client.ResourceBackClientContent.ResourceTypeObjOrBuilder getObjsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.ResourceBackModuleObjClientProto}
   *
   * <pre>
   * </pre>
   */
  public static final class ResourceBackModuleObjClientProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.ResourceBackModuleObjClientProto)
      ResourceBackModuleObjClientProtoOrBuilder {
    // Use ResourceBackModuleObjClientProto.newBuilder() to construct.
    private ResourceBackModuleObjClientProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResourceBackModuleObjClientProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResourceBackModuleObjClientProto defaultInstance;
    public static ResourceBackModuleObjClientProto getDefaultInstance() {
      return defaultInstance;
    }

    public ResourceBackModuleObjClientProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResourceBackModuleObjClientProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              updateRemainTimesLevel_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                objs_ = new java.util.ArrayList<app.protobuf.client.ResourceBackClientContent.ResourceTypeObj>();
                mutable_bitField0_ |= 0x00000002;
              }
              objs_.add(input.readMessage(app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          objs_ = java.util.Collections.unmodifiableList(objs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return app.protobuf.client.ResourceBackClientContent.internal_static_proto_ResourceBackModuleObjClientProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return app.protobuf.client.ResourceBackClientContent.internal_static_proto_ResourceBackModuleObjClientProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto.class, app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto.Builder.class);
    }

    public static com.google.protobuf.Parser<ResourceBackModuleObjClientProto> PARSER =
        new com.google.protobuf.AbstractParser<ResourceBackModuleObjClientProto>() {
      public ResourceBackModuleObjClientProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResourceBackModuleObjClientProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResourceBackModuleObjClientProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int UPDATEREMAINTIMESLEVEL_FIELD_NUMBER = 1;
    private int updateRemainTimesLevel_;
    /**
     * <code>optional int32 updateRemainTimesLevel = 1;</code>
     *
     * <pre>
     *最后一次更新资源可找回次数时的等级，根据这个显示奖励
     * </pre>
     */
    public boolean hasUpdateRemainTimesLevel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 updateRemainTimesLevel = 1;</code>
     *
     * <pre>
     *最后一次更新资源可找回次数时的等级，根据这个显示奖励
     * </pre>
     */
    public int getUpdateRemainTimesLevel() {
      return updateRemainTimesLevel_;
    }

    public static final int OBJS_FIELD_NUMBER = 2;
    private java.util.List<app.protobuf.client.ResourceBackClientContent.ResourceTypeObj> objs_;
    /**
     * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
     */
    public java.util.List<app.protobuf.client.ResourceBackClientContent.ResourceTypeObj> getObjsList() {
      return objs_;
    }
    /**
     * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
     */
    public java.util.List<? extends app.protobuf.client.ResourceBackClientContent.ResourceTypeObjOrBuilder> 
        getObjsOrBuilderList() {
      return objs_;
    }
    /**
     * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
     */
    public int getObjsCount() {
      return objs_.size();
    }
    /**
     * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
     */
    public app.protobuf.client.ResourceBackClientContent.ResourceTypeObj getObjs(int index) {
      return objs_.get(index);
    }
    /**
     * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
     */
    public app.protobuf.client.ResourceBackClientContent.ResourceTypeObjOrBuilder getObjsOrBuilder(
        int index) {
      return objs_.get(index);
    }

    private void initFields() {
      updateRemainTimesLevel_ = 0;
      objs_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, updateRemainTimesLevel_);
      }
      for (int i = 0; i < objs_.size(); i++) {
        output.writeMessage(2, objs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, updateRemainTimesLevel_);
      }
      for (int i = 0; i < objs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, objs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ResourceBackModuleObjClientProto}
     *
     * <pre>
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ResourceBackModuleObjClientProto)
        app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return app.protobuf.client.ResourceBackClientContent.internal_static_proto_ResourceBackModuleObjClientProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return app.protobuf.client.ResourceBackClientContent.internal_static_proto_ResourceBackModuleObjClientProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto.class, app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto.Builder.class);
      }

      // Construct using app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getObjsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        updateRemainTimesLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (objsBuilder_ == null) {
          objs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          objsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return app.protobuf.client.ResourceBackClientContent.internal_static_proto_ResourceBackModuleObjClientProto_descriptor;
      }

      public app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto getDefaultInstanceForType() {
        return app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto.getDefaultInstance();
      }

      public app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto build() {
        app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto buildPartial() {
        app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto result = new app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.updateRemainTimesLevel_ = updateRemainTimesLevel_;
        if (objsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            objs_ = java.util.Collections.unmodifiableList(objs_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.objs_ = objs_;
        } else {
          result.objs_ = objsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto) {
          return mergeFrom((app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto other) {
        if (other == app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto.getDefaultInstance()) return this;
        if (other.hasUpdateRemainTimesLevel()) {
          setUpdateRemainTimesLevel(other.getUpdateRemainTimesLevel());
        }
        if (objsBuilder_ == null) {
          if (!other.objs_.isEmpty()) {
            if (objs_.isEmpty()) {
              objs_ = other.objs_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureObjsIsMutable();
              objs_.addAll(other.objs_);
            }
            onChanged();
          }
        } else {
          if (!other.objs_.isEmpty()) {
            if (objsBuilder_.isEmpty()) {
              objsBuilder_.dispose();
              objsBuilder_ = null;
              objs_ = other.objs_;
              bitField0_ = (bitField0_ & ~0x00000002);
              objsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getObjsFieldBuilder() : null;
            } else {
              objsBuilder_.addAllMessages(other.objs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (app.protobuf.client.ResourceBackClientContent.ResourceBackModuleObjClientProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int updateRemainTimesLevel_ ;
      /**
       * <code>optional int32 updateRemainTimesLevel = 1;</code>
       *
       * <pre>
       *最后一次更新资源可找回次数时的等级，根据这个显示奖励
       * </pre>
       */
      public boolean hasUpdateRemainTimesLevel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 updateRemainTimesLevel = 1;</code>
       *
       * <pre>
       *最后一次更新资源可找回次数时的等级，根据这个显示奖励
       * </pre>
       */
      public int getUpdateRemainTimesLevel() {
        return updateRemainTimesLevel_;
      }
      /**
       * <code>optional int32 updateRemainTimesLevel = 1;</code>
       *
       * <pre>
       *最后一次更新资源可找回次数时的等级，根据这个显示奖励
       * </pre>
       */
      public Builder setUpdateRemainTimesLevel(int value) {
        bitField0_ |= 0x00000001;
        updateRemainTimesLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 updateRemainTimesLevel = 1;</code>
       *
       * <pre>
       *最后一次更新资源可找回次数时的等级，根据这个显示奖励
       * </pre>
       */
      public Builder clearUpdateRemainTimesLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        updateRemainTimesLevel_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<app.protobuf.client.ResourceBackClientContent.ResourceTypeObj> objs_ =
        java.util.Collections.emptyList();
      private void ensureObjsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          objs_ = new java.util.ArrayList<app.protobuf.client.ResourceBackClientContent.ResourceTypeObj>(objs_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          app.protobuf.client.ResourceBackClientContent.ResourceTypeObj, app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.Builder, app.protobuf.client.ResourceBackClientContent.ResourceTypeObjOrBuilder> objsBuilder_;

      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public java.util.List<app.protobuf.client.ResourceBackClientContent.ResourceTypeObj> getObjsList() {
        if (objsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(objs_);
        } else {
          return objsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public int getObjsCount() {
        if (objsBuilder_ == null) {
          return objs_.size();
        } else {
          return objsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public app.protobuf.client.ResourceBackClientContent.ResourceTypeObj getObjs(int index) {
        if (objsBuilder_ == null) {
          return objs_.get(index);
        } else {
          return objsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public Builder setObjs(
          int index, app.protobuf.client.ResourceBackClientContent.ResourceTypeObj value) {
        if (objsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjsIsMutable();
          objs_.set(index, value);
          onChanged();
        } else {
          objsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public Builder setObjs(
          int index, app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.Builder builderForValue) {
        if (objsBuilder_ == null) {
          ensureObjsIsMutable();
          objs_.set(index, builderForValue.build());
          onChanged();
        } else {
          objsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public Builder addObjs(app.protobuf.client.ResourceBackClientContent.ResourceTypeObj value) {
        if (objsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjsIsMutable();
          objs_.add(value);
          onChanged();
        } else {
          objsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public Builder addObjs(
          int index, app.protobuf.client.ResourceBackClientContent.ResourceTypeObj value) {
        if (objsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjsIsMutable();
          objs_.add(index, value);
          onChanged();
        } else {
          objsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public Builder addObjs(
          app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.Builder builderForValue) {
        if (objsBuilder_ == null) {
          ensureObjsIsMutable();
          objs_.add(builderForValue.build());
          onChanged();
        } else {
          objsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public Builder addObjs(
          int index, app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.Builder builderForValue) {
        if (objsBuilder_ == null) {
          ensureObjsIsMutable();
          objs_.add(index, builderForValue.build());
          onChanged();
        } else {
          objsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public Builder addAllObjs(
          java.lang.Iterable<? extends app.protobuf.client.ResourceBackClientContent.ResourceTypeObj> values) {
        if (objsBuilder_ == null) {
          ensureObjsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, objs_);
          onChanged();
        } else {
          objsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public Builder clearObjs() {
        if (objsBuilder_ == null) {
          objs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          objsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public Builder removeObjs(int index) {
        if (objsBuilder_ == null) {
          ensureObjsIsMutable();
          objs_.remove(index);
          onChanged();
        } else {
          objsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.Builder getObjsBuilder(
          int index) {
        return getObjsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public app.protobuf.client.ResourceBackClientContent.ResourceTypeObjOrBuilder getObjsOrBuilder(
          int index) {
        if (objsBuilder_ == null) {
          return objs_.get(index);  } else {
          return objsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public java.util.List<? extends app.protobuf.client.ResourceBackClientContent.ResourceTypeObjOrBuilder> 
           getObjsOrBuilderList() {
        if (objsBuilder_ != null) {
          return objsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(objs_);
        }
      }
      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.Builder addObjsBuilder() {
        return getObjsFieldBuilder().addBuilder(
            app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.Builder addObjsBuilder(
          int index) {
        return getObjsFieldBuilder().addBuilder(
            index, app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.ResourceTypeObj objs = 2;</code>
       */
      public java.util.List<app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.Builder> 
           getObjsBuilderList() {
        return getObjsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          app.protobuf.client.ResourceBackClientContent.ResourceTypeObj, app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.Builder, app.protobuf.client.ResourceBackClientContent.ResourceTypeObjOrBuilder> 
          getObjsFieldBuilder() {
        if (objsBuilder_ == null) {
          objsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              app.protobuf.client.ResourceBackClientContent.ResourceTypeObj, app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.Builder, app.protobuf.client.ResourceBackClientContent.ResourceTypeObjOrBuilder>(
                  objs_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          objs_ = null;
        }
        return objsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.ResourceBackModuleObjClientProto)
    }

    static {
      defaultInstance = new ResourceBackModuleObjClientProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.ResourceBackModuleObjClientProto)
  }

  public interface ResourceTypeObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ResourceTypeObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     *资源找回配置ID
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     *资源找回配置ID
     * </pre>
     */
    int getId();

    /**
     * <code>optional int32 normal_times = 2;</code>
     *
     * <pre>
     *普通可找回次数
     * </pre>
     */
    boolean hasNormalTimes();
    /**
     * <code>optional int32 normal_times = 2;</code>
     *
     * <pre>
     *普通可找回次数
     * </pre>
     */
    int getNormalTimes();

    /**
     * <code>optional int32 external_times = 3;</code>
     *
     * <pre>
     *额外可找回次数
     * </pre>
     */
    boolean hasExternalTimes();
    /**
     * <code>optional int32 external_times = 3;</code>
     *
     * <pre>
     *额外可找回次数
     * </pre>
     */
    int getExternalTimes();
  }
  /**
   * Protobuf type {@code proto.ResourceTypeObj}
   *
   * <pre>
   *各类型找回次数统计出来的数据
   * </pre>
   */
  public static final class ResourceTypeObj extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.ResourceTypeObj)
      ResourceTypeObjOrBuilder {
    // Use ResourceTypeObj.newBuilder() to construct.
    private ResourceTypeObj(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResourceTypeObj(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResourceTypeObj defaultInstance;
    public static ResourceTypeObj getDefaultInstance() {
      return defaultInstance;
    }

    public ResourceTypeObj getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResourceTypeObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              normalTimes_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              externalTimes_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return app.protobuf.client.ResourceBackClientContent.internal_static_proto_ResourceTypeObj_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return app.protobuf.client.ResourceBackClientContent.internal_static_proto_ResourceTypeObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.class, app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.Builder.class);
    }

    public static com.google.protobuf.Parser<ResourceTypeObj> PARSER =
        new com.google.protobuf.AbstractParser<ResourceTypeObj>() {
      public ResourceTypeObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResourceTypeObj(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResourceTypeObj> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     *资源找回配置ID
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     *资源找回配置ID
     * </pre>
     */
    public int getId() {
      return id_;
    }

    public static final int NORMAL_TIMES_FIELD_NUMBER = 2;
    private int normalTimes_;
    /**
     * <code>optional int32 normal_times = 2;</code>
     *
     * <pre>
     *普通可找回次数
     * </pre>
     */
    public boolean hasNormalTimes() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 normal_times = 2;</code>
     *
     * <pre>
     *普通可找回次数
     * </pre>
     */
    public int getNormalTimes() {
      return normalTimes_;
    }

    public static final int EXTERNAL_TIMES_FIELD_NUMBER = 3;
    private int externalTimes_;
    /**
     * <code>optional int32 external_times = 3;</code>
     *
     * <pre>
     *额外可找回次数
     * </pre>
     */
    public boolean hasExternalTimes() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 external_times = 3;</code>
     *
     * <pre>
     *额外可找回次数
     * </pre>
     */
    public int getExternalTimes() {
      return externalTimes_;
    }

    private void initFields() {
      id_ = 0;
      normalTimes_ = 0;
      externalTimes_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, normalTimes_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, externalTimes_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, normalTimes_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, externalTimes_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static app.protobuf.client.ResourceBackClientContent.ResourceTypeObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceTypeObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceTypeObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceTypeObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceTypeObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceTypeObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceTypeObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceTypeObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceTypeObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.client.ResourceBackClientContent.ResourceTypeObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(app.protobuf.client.ResourceBackClientContent.ResourceTypeObj prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ResourceTypeObj}
     *
     * <pre>
     *各类型找回次数统计出来的数据
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ResourceTypeObj)
        app.protobuf.client.ResourceBackClientContent.ResourceTypeObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return app.protobuf.client.ResourceBackClientContent.internal_static_proto_ResourceTypeObj_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return app.protobuf.client.ResourceBackClientContent.internal_static_proto_ResourceTypeObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.class, app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.Builder.class);
      }

      // Construct using app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        normalTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        externalTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return app.protobuf.client.ResourceBackClientContent.internal_static_proto_ResourceTypeObj_descriptor;
      }

      public app.protobuf.client.ResourceBackClientContent.ResourceTypeObj getDefaultInstanceForType() {
        return app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.getDefaultInstance();
      }

      public app.protobuf.client.ResourceBackClientContent.ResourceTypeObj build() {
        app.protobuf.client.ResourceBackClientContent.ResourceTypeObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public app.protobuf.client.ResourceBackClientContent.ResourceTypeObj buildPartial() {
        app.protobuf.client.ResourceBackClientContent.ResourceTypeObj result = new app.protobuf.client.ResourceBackClientContent.ResourceTypeObj(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.normalTimes_ = normalTimes_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.externalTimes_ = externalTimes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof app.protobuf.client.ResourceBackClientContent.ResourceTypeObj) {
          return mergeFrom((app.protobuf.client.ResourceBackClientContent.ResourceTypeObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(app.protobuf.client.ResourceBackClientContent.ResourceTypeObj other) {
        if (other == app.protobuf.client.ResourceBackClientContent.ResourceTypeObj.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasNormalTimes()) {
          setNormalTimes(other.getNormalTimes());
        }
        if (other.hasExternalTimes()) {
          setExternalTimes(other.getExternalTimes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        app.protobuf.client.ResourceBackClientContent.ResourceTypeObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (app.protobuf.client.ResourceBackClientContent.ResourceTypeObj) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       *
       * <pre>
       *资源找回配置ID
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       *
       * <pre>
       *资源找回配置ID
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       *
       * <pre>
       *资源找回配置ID
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       *
       * <pre>
       *资源找回配置ID
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int normalTimes_ ;
      /**
       * <code>optional int32 normal_times = 2;</code>
       *
       * <pre>
       *普通可找回次数
       * </pre>
       */
      public boolean hasNormalTimes() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 normal_times = 2;</code>
       *
       * <pre>
       *普通可找回次数
       * </pre>
       */
      public int getNormalTimes() {
        return normalTimes_;
      }
      /**
       * <code>optional int32 normal_times = 2;</code>
       *
       * <pre>
       *普通可找回次数
       * </pre>
       */
      public Builder setNormalTimes(int value) {
        bitField0_ |= 0x00000002;
        normalTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 normal_times = 2;</code>
       *
       * <pre>
       *普通可找回次数
       * </pre>
       */
      public Builder clearNormalTimes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        normalTimes_ = 0;
        onChanged();
        return this;
      }

      private int externalTimes_ ;
      /**
       * <code>optional int32 external_times = 3;</code>
       *
       * <pre>
       *额外可找回次数
       * </pre>
       */
      public boolean hasExternalTimes() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 external_times = 3;</code>
       *
       * <pre>
       *额外可找回次数
       * </pre>
       */
      public int getExternalTimes() {
        return externalTimes_;
      }
      /**
       * <code>optional int32 external_times = 3;</code>
       *
       * <pre>
       *额外可找回次数
       * </pre>
       */
      public Builder setExternalTimes(int value) {
        bitField0_ |= 0x00000004;
        externalTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 external_times = 3;</code>
       *
       * <pre>
       *额外可找回次数
       * </pre>
       */
      public Builder clearExternalTimes() {
        bitField0_ = (bitField0_ & ~0x00000004);
        externalTimes_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.ResourceTypeObj)
    }

    static {
      defaultInstance = new ResourceTypeObj(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.ResourceTypeObj)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ResourceBackModuleObjClientProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ResourceBackModuleObjClientProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ResourceTypeObj_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ResourceTypeObj_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!client/resource_back_client.proto\022\005pro" +
      "to\"h\n ResourceBackModuleObjClientProto\022\036" +
      "\n\026updateRemainTimesLevel\030\001 \001(\005\022$\n\004objs\030\002" +
      " \003(\0132\026.proto.ResourceTypeObj\"K\n\017Resource" +
      "TypeObj\022\n\n\002id\030\001 \001(\005\022\024\n\014normal_times\030\002 \001(" +
      "\005\022\026\n\016external_times\030\003 \001(\005B2\n\023app.protobu" +
      "f.clientB\031ResourceBackClientContentH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_ResourceBackModuleObjClientProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ResourceBackModuleObjClientProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_ResourceBackModuleObjClientProto_descriptor,
        new java.lang.String[] { "UpdateRemainTimesLevel", "Objs", });
    internal_static_proto_ResourceTypeObj_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ResourceTypeObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_ResourceTypeObj_descriptor,
        new java.lang.String[] { "Id", "NormalTimes", "ExternalTimes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
