// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/guild_exam_server.proto

package app.protobuf.server;

public final class GuildExamServerContent {
  private GuildExamServerContent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GuildExamModuleObjMinorProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.GuildExamModuleObjMinorProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 last_join_activity_time = 1;</code>
     *
     * <pre>
     *最后一次加入活动，还没有结算的时间
     * </pre>
     */
    boolean hasLastJoinActivityTime();
    /**
     * <code>optional int64 last_join_activity_time = 1;</code>
     *
     * <pre>
     *最后一次加入活动，还没有结算的时间
     * </pre>
     */
    long getLastJoinActivityTime();

    /**
     * <code>optional int64 guild_exam_scene_exp = 2;</code>
     *
     * <pre>
     *最后一次加入活动，还没有结算的经验
     * </pre>
     */
    boolean hasGuildExamSceneExp();
    /**
     * <code>optional int64 guild_exam_scene_exp = 2;</code>
     *
     * <pre>
     *最后一次加入活动，还没有结算的经验
     * </pre>
     */
    long getGuildExamSceneExp();

    /**
     * <code>optional int64 guild_exam_scene_contribution = 3;</code>
     *
     * <pre>
     *最后一次加入活动，还没有结算的帮贡
     * </pre>
     */
    boolean hasGuildExamSceneContribution();
    /**
     * <code>optional int64 guild_exam_scene_contribution = 3;</code>
     *
     * <pre>
     *最后一次加入活动，还没有结算的帮贡
     * </pre>
     */
    long getGuildExamSceneContribution();

    /**
     * <code>optional int64 last_collect_time = 4;</code>
     *
     * <pre>
     *客户端用来判断本次答题是不是已经采集过了(因为一次活动只能采集一次)
     * </pre>
     */
    boolean hasLastCollectTime();
    /**
     * <code>optional int64 last_collect_time = 4;</code>
     *
     * <pre>
     *客户端用来判断本次答题是不是已经采集过了(因为一次活动只能采集一次)
     * </pre>
     */
    long getLastCollectTime();
  }
  /**
   * Protobuf type {@code proto.GuildExamModuleObjMinorProto}
   *
   * <pre>
   * </pre>
   */
  public static final class GuildExamModuleObjMinorProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.GuildExamModuleObjMinorProto)
      GuildExamModuleObjMinorProtoOrBuilder {
    // Use GuildExamModuleObjMinorProto.newBuilder() to construct.
    private GuildExamModuleObjMinorProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GuildExamModuleObjMinorProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GuildExamModuleObjMinorProto defaultInstance;
    public static GuildExamModuleObjMinorProto getDefaultInstance() {
      return defaultInstance;
    }

    public GuildExamModuleObjMinorProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GuildExamModuleObjMinorProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              lastJoinActivityTime_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              guildExamSceneExp_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              guildExamSceneContribution_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              lastCollectTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return app.protobuf.server.GuildExamServerContent.internal_static_proto_GuildExamModuleObjMinorProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return app.protobuf.server.GuildExamServerContent.internal_static_proto_GuildExamModuleObjMinorProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto.class, app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto.Builder.class);
    }

    public static com.google.protobuf.Parser<GuildExamModuleObjMinorProto> PARSER =
        new com.google.protobuf.AbstractParser<GuildExamModuleObjMinorProto>() {
      public GuildExamModuleObjMinorProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GuildExamModuleObjMinorProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GuildExamModuleObjMinorProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int LAST_JOIN_ACTIVITY_TIME_FIELD_NUMBER = 1;
    private long lastJoinActivityTime_;
    /**
     * <code>optional int64 last_join_activity_time = 1;</code>
     *
     * <pre>
     *最后一次加入活动，还没有结算的时间
     * </pre>
     */
    public boolean hasLastJoinActivityTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 last_join_activity_time = 1;</code>
     *
     * <pre>
     *最后一次加入活动，还没有结算的时间
     * </pre>
     */
    public long getLastJoinActivityTime() {
      return lastJoinActivityTime_;
    }

    public static final int GUILD_EXAM_SCENE_EXP_FIELD_NUMBER = 2;
    private long guildExamSceneExp_;
    /**
     * <code>optional int64 guild_exam_scene_exp = 2;</code>
     *
     * <pre>
     *最后一次加入活动，还没有结算的经验
     * </pre>
     */
    public boolean hasGuildExamSceneExp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 guild_exam_scene_exp = 2;</code>
     *
     * <pre>
     *最后一次加入活动，还没有结算的经验
     * </pre>
     */
    public long getGuildExamSceneExp() {
      return guildExamSceneExp_;
    }

    public static final int GUILD_EXAM_SCENE_CONTRIBUTION_FIELD_NUMBER = 3;
    private long guildExamSceneContribution_;
    /**
     * <code>optional int64 guild_exam_scene_contribution = 3;</code>
     *
     * <pre>
     *最后一次加入活动，还没有结算的帮贡
     * </pre>
     */
    public boolean hasGuildExamSceneContribution() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 guild_exam_scene_contribution = 3;</code>
     *
     * <pre>
     *最后一次加入活动，还没有结算的帮贡
     * </pre>
     */
    public long getGuildExamSceneContribution() {
      return guildExamSceneContribution_;
    }

    public static final int LAST_COLLECT_TIME_FIELD_NUMBER = 4;
    private long lastCollectTime_;
    /**
     * <code>optional int64 last_collect_time = 4;</code>
     *
     * <pre>
     *客户端用来判断本次答题是不是已经采集过了(因为一次活动只能采集一次)
     * </pre>
     */
    public boolean hasLastCollectTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 last_collect_time = 4;</code>
     *
     * <pre>
     *客户端用来判断本次答题是不是已经采集过了(因为一次活动只能采集一次)
     * </pre>
     */
    public long getLastCollectTime() {
      return lastCollectTime_;
    }

    private void initFields() {
      lastJoinActivityTime_ = 0L;
      guildExamSceneExp_ = 0L;
      guildExamSceneContribution_ = 0L;
      lastCollectTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, lastJoinActivityTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, guildExamSceneExp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, guildExamSceneContribution_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, lastCollectTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, lastJoinActivityTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, guildExamSceneExp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, guildExamSceneContribution_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, lastCollectTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.GuildExamModuleObjMinorProto}
     *
     * <pre>
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.GuildExamModuleObjMinorProto)
        app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return app.protobuf.server.GuildExamServerContent.internal_static_proto_GuildExamModuleObjMinorProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return app.protobuf.server.GuildExamServerContent.internal_static_proto_GuildExamModuleObjMinorProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto.class, app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto.Builder.class);
      }

      // Construct using app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        lastJoinActivityTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        guildExamSceneExp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        guildExamSceneContribution_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        lastCollectTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return app.protobuf.server.GuildExamServerContent.internal_static_proto_GuildExamModuleObjMinorProto_descriptor;
      }

      public app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto getDefaultInstanceForType() {
        return app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto.getDefaultInstance();
      }

      public app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto build() {
        app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto buildPartial() {
        app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto result = new app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lastJoinActivityTime_ = lastJoinActivityTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.guildExamSceneExp_ = guildExamSceneExp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.guildExamSceneContribution_ = guildExamSceneContribution_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lastCollectTime_ = lastCollectTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto) {
          return mergeFrom((app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto other) {
        if (other == app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto.getDefaultInstance()) return this;
        if (other.hasLastJoinActivityTime()) {
          setLastJoinActivityTime(other.getLastJoinActivityTime());
        }
        if (other.hasGuildExamSceneExp()) {
          setGuildExamSceneExp(other.getGuildExamSceneExp());
        }
        if (other.hasGuildExamSceneContribution()) {
          setGuildExamSceneContribution(other.getGuildExamSceneContribution());
        }
        if (other.hasLastCollectTime()) {
          setLastCollectTime(other.getLastCollectTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (app.protobuf.server.GuildExamServerContent.GuildExamModuleObjMinorProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long lastJoinActivityTime_ ;
      /**
       * <code>optional int64 last_join_activity_time = 1;</code>
       *
       * <pre>
       *最后一次加入活动，还没有结算的时间
       * </pre>
       */
      public boolean hasLastJoinActivityTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 last_join_activity_time = 1;</code>
       *
       * <pre>
       *最后一次加入活动，还没有结算的时间
       * </pre>
       */
      public long getLastJoinActivityTime() {
        return lastJoinActivityTime_;
      }
      /**
       * <code>optional int64 last_join_activity_time = 1;</code>
       *
       * <pre>
       *最后一次加入活动，还没有结算的时间
       * </pre>
       */
      public Builder setLastJoinActivityTime(long value) {
        bitField0_ |= 0x00000001;
        lastJoinActivityTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 last_join_activity_time = 1;</code>
       *
       * <pre>
       *最后一次加入活动，还没有结算的时间
       * </pre>
       */
      public Builder clearLastJoinActivityTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lastJoinActivityTime_ = 0L;
        onChanged();
        return this;
      }

      private long guildExamSceneExp_ ;
      /**
       * <code>optional int64 guild_exam_scene_exp = 2;</code>
       *
       * <pre>
       *最后一次加入活动，还没有结算的经验
       * </pre>
       */
      public boolean hasGuildExamSceneExp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 guild_exam_scene_exp = 2;</code>
       *
       * <pre>
       *最后一次加入活动，还没有结算的经验
       * </pre>
       */
      public long getGuildExamSceneExp() {
        return guildExamSceneExp_;
      }
      /**
       * <code>optional int64 guild_exam_scene_exp = 2;</code>
       *
       * <pre>
       *最后一次加入活动，还没有结算的经验
       * </pre>
       */
      public Builder setGuildExamSceneExp(long value) {
        bitField0_ |= 0x00000002;
        guildExamSceneExp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 guild_exam_scene_exp = 2;</code>
       *
       * <pre>
       *最后一次加入活动，还没有结算的经验
       * </pre>
       */
      public Builder clearGuildExamSceneExp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        guildExamSceneExp_ = 0L;
        onChanged();
        return this;
      }

      private long guildExamSceneContribution_ ;
      /**
       * <code>optional int64 guild_exam_scene_contribution = 3;</code>
       *
       * <pre>
       *最后一次加入活动，还没有结算的帮贡
       * </pre>
       */
      public boolean hasGuildExamSceneContribution() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 guild_exam_scene_contribution = 3;</code>
       *
       * <pre>
       *最后一次加入活动，还没有结算的帮贡
       * </pre>
       */
      public long getGuildExamSceneContribution() {
        return guildExamSceneContribution_;
      }
      /**
       * <code>optional int64 guild_exam_scene_contribution = 3;</code>
       *
       * <pre>
       *最后一次加入活动，还没有结算的帮贡
       * </pre>
       */
      public Builder setGuildExamSceneContribution(long value) {
        bitField0_ |= 0x00000004;
        guildExamSceneContribution_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 guild_exam_scene_contribution = 3;</code>
       *
       * <pre>
       *最后一次加入活动，还没有结算的帮贡
       * </pre>
       */
      public Builder clearGuildExamSceneContribution() {
        bitField0_ = (bitField0_ & ~0x00000004);
        guildExamSceneContribution_ = 0L;
        onChanged();
        return this;
      }

      private long lastCollectTime_ ;
      /**
       * <code>optional int64 last_collect_time = 4;</code>
       *
       * <pre>
       *客户端用来判断本次答题是不是已经采集过了(因为一次活动只能采集一次)
       * </pre>
       */
      public boolean hasLastCollectTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 last_collect_time = 4;</code>
       *
       * <pre>
       *客户端用来判断本次答题是不是已经采集过了(因为一次活动只能采集一次)
       * </pre>
       */
      public long getLastCollectTime() {
        return lastCollectTime_;
      }
      /**
       * <code>optional int64 last_collect_time = 4;</code>
       *
       * <pre>
       *客户端用来判断本次答题是不是已经采集过了(因为一次活动只能采集一次)
       * </pre>
       */
      public Builder setLastCollectTime(long value) {
        bitField0_ |= 0x00000008;
        lastCollectTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 last_collect_time = 4;</code>
       *
       * <pre>
       *客户端用来判断本次答题是不是已经采集过了(因为一次活动只能采集一次)
       * </pre>
       */
      public Builder clearLastCollectTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lastCollectTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.GuildExamModuleObjMinorProto)
    }

    static {
      defaultInstance = new GuildExamModuleObjMinorProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.GuildExamModuleObjMinorProto)
  }

  public interface GuildSingleExamInfoProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.GuildSingleExamInfoProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 activity_start_time = 1;</code>
     *
     * <pre>
     *上次关服时活动开启时间
     * </pre>
     */
    boolean hasActivityStartTime();
    /**
     * <code>optional int64 activity_start_time = 1;</code>
     *
     * <pre>
     *上次关服时活动开启时间
     * </pre>
     */
    long getActivityStartTime();

    /**
     * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
     */
    java.util.List<app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto> 
        getGuildList();
    /**
     * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
     */
    app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto getGuild(int index);
    /**
     * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
     */
    int getGuildCount();
    /**
     * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
     */
    java.util.List<? extends app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProtoOrBuilder> 
        getGuildOrBuilderList();
    /**
     * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
     */
    app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProtoOrBuilder getGuildOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.GuildSingleExamInfoProto}
   */
  public static final class GuildSingleExamInfoProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.GuildSingleExamInfoProto)
      GuildSingleExamInfoProtoOrBuilder {
    // Use GuildSingleExamInfoProto.newBuilder() to construct.
    private GuildSingleExamInfoProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GuildSingleExamInfoProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GuildSingleExamInfoProto defaultInstance;
    public static GuildSingleExamInfoProto getDefaultInstance() {
      return defaultInstance;
    }

    public GuildSingleExamInfoProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GuildSingleExamInfoProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              activityStartTime_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                guild_ = new java.util.ArrayList<app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto>();
                mutable_bitField0_ |= 0x00000002;
              }
              guild_.add(input.readMessage(app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          guild_ = java.util.Collections.unmodifiableList(guild_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return app.protobuf.server.GuildExamServerContent.internal_static_proto_GuildSingleExamInfoProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return app.protobuf.server.GuildExamServerContent.internal_static_proto_GuildSingleExamInfoProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.class, app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.Builder.class);
    }

    public static com.google.protobuf.Parser<GuildSingleExamInfoProto> PARSER =
        new com.google.protobuf.AbstractParser<GuildSingleExamInfoProto>() {
      public GuildSingleExamInfoProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GuildSingleExamInfoProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GuildSingleExamInfoProto> getParserForType() {
      return PARSER;
    }

    public interface RankGuildExamInfoProtoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:proto.GuildSingleExamInfoProto.RankGuildExamInfoProto)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int64 guildId = 1;</code>
       */
      boolean hasGuildId();
      /**
       * <code>optional int64 guildId = 1;</code>
       */
      long getGuildId();

      /**
       * <code>optional int32 score = 3;</code>
       */
      boolean hasScore();
      /**
       * <code>optional int32 score = 3;</code>
       */
      int getScore();

      /**
       * <code>optional int64 scoreUpdateTime = 4;</code>
       */
      boolean hasScoreUpdateTime();
      /**
       * <code>optional int64 scoreUpdateTime = 4;</code>
       */
      long getScoreUpdateTime();
    }
    /**
     * Protobuf type {@code proto.GuildSingleExamInfoProto.RankGuildExamInfoProto}
     */
    public static final class RankGuildExamInfoProto extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:proto.GuildSingleExamInfoProto.RankGuildExamInfoProto)
        RankGuildExamInfoProtoOrBuilder {
      // Use RankGuildExamInfoProto.newBuilder() to construct.
      private RankGuildExamInfoProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private RankGuildExamInfoProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final RankGuildExamInfoProto defaultInstance;
      public static RankGuildExamInfoProto getDefaultInstance() {
        return defaultInstance;
      }

      public RankGuildExamInfoProto getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private RankGuildExamInfoProto(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                guildId_ = input.readInt64();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000002;
                score_ = input.readInt32();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000004;
                scoreUpdateTime_ = input.readInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return app.protobuf.server.GuildExamServerContent.internal_static_proto_GuildSingleExamInfoProto_RankGuildExamInfoProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return app.protobuf.server.GuildExamServerContent.internal_static_proto_GuildSingleExamInfoProto_RankGuildExamInfoProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.class, app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.Builder.class);
      }

      public static com.google.protobuf.Parser<RankGuildExamInfoProto> PARSER =
          new com.google.protobuf.AbstractParser<RankGuildExamInfoProto>() {
        public RankGuildExamInfoProto parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new RankGuildExamInfoProto(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<RankGuildExamInfoProto> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int GUILDID_FIELD_NUMBER = 1;
      private long guildId_;
      /**
       * <code>optional int64 guildId = 1;</code>
       */
      public boolean hasGuildId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 guildId = 1;</code>
       */
      public long getGuildId() {
        return guildId_;
      }

      public static final int SCORE_FIELD_NUMBER = 3;
      private int score_;
      /**
       * <code>optional int32 score = 3;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 score = 3;</code>
       */
      public int getScore() {
        return score_;
      }

      public static final int SCOREUPDATETIME_FIELD_NUMBER = 4;
      private long scoreUpdateTime_;
      /**
       * <code>optional int64 scoreUpdateTime = 4;</code>
       */
      public boolean hasScoreUpdateTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 scoreUpdateTime = 4;</code>
       */
      public long getScoreUpdateTime() {
        return scoreUpdateTime_;
      }

      private void initFields() {
        guildId_ = 0L;
        score_ = 0;
        scoreUpdateTime_ = 0L;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt64(1, guildId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(3, score_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt64(4, scoreUpdateTime_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, guildId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, score_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(4, scoreUpdateTime_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code proto.GuildSingleExamInfoProto.RankGuildExamInfoProto}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:proto.GuildSingleExamInfoProto.RankGuildExamInfoProto)
          app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProtoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return app.protobuf.server.GuildExamServerContent.internal_static_proto_GuildSingleExamInfoProto_RankGuildExamInfoProto_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return app.protobuf.server.GuildExamServerContent.internal_static_proto_GuildSingleExamInfoProto_RankGuildExamInfoProto_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.class, app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.Builder.class);
        }

        // Construct using app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          guildId_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          score_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          scoreUpdateTime_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return app.protobuf.server.GuildExamServerContent.internal_static_proto_GuildSingleExamInfoProto_RankGuildExamInfoProto_descriptor;
        }

        public app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto getDefaultInstanceForType() {
          return app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.getDefaultInstance();
        }

        public app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto build() {
          app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto buildPartial() {
          app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto result = new app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.guildId_ = guildId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.score_ = score_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.scoreUpdateTime_ = scoreUpdateTime_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto) {
            return mergeFrom((app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto other) {
          if (other == app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.getDefaultInstance()) return this;
          if (other.hasGuildId()) {
            setGuildId(other.getGuildId());
          }
          if (other.hasScore()) {
            setScore(other.getScore());
          }
          if (other.hasScoreUpdateTime()) {
            setScoreUpdateTime(other.getScoreUpdateTime());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private long guildId_ ;
        /**
         * <code>optional int64 guildId = 1;</code>
         */
        public boolean hasGuildId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int64 guildId = 1;</code>
         */
        public long getGuildId() {
          return guildId_;
        }
        /**
         * <code>optional int64 guildId = 1;</code>
         */
        public Builder setGuildId(long value) {
          bitField0_ |= 0x00000001;
          guildId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 guildId = 1;</code>
         */
        public Builder clearGuildId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          guildId_ = 0L;
          onChanged();
          return this;
        }

        private int score_ ;
        /**
         * <code>optional int32 score = 3;</code>
         */
        public boolean hasScore() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int32 score = 3;</code>
         */
        public int getScore() {
          return score_;
        }
        /**
         * <code>optional int32 score = 3;</code>
         */
        public Builder setScore(int value) {
          bitField0_ |= 0x00000002;
          score_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 score = 3;</code>
         */
        public Builder clearScore() {
          bitField0_ = (bitField0_ & ~0x00000002);
          score_ = 0;
          onChanged();
          return this;
        }

        private long scoreUpdateTime_ ;
        /**
         * <code>optional int64 scoreUpdateTime = 4;</code>
         */
        public boolean hasScoreUpdateTime() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int64 scoreUpdateTime = 4;</code>
         */
        public long getScoreUpdateTime() {
          return scoreUpdateTime_;
        }
        /**
         * <code>optional int64 scoreUpdateTime = 4;</code>
         */
        public Builder setScoreUpdateTime(long value) {
          bitField0_ |= 0x00000004;
          scoreUpdateTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 scoreUpdateTime = 4;</code>
         */
        public Builder clearScoreUpdateTime() {
          bitField0_ = (bitField0_ & ~0x00000004);
          scoreUpdateTime_ = 0L;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:proto.GuildSingleExamInfoProto.RankGuildExamInfoProto)
      }

      static {
        defaultInstance = new RankGuildExamInfoProto(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:proto.GuildSingleExamInfoProto.RankGuildExamInfoProto)
    }

    private int bitField0_;
    public static final int ACTIVITY_START_TIME_FIELD_NUMBER = 1;
    private long activityStartTime_;
    /**
     * <code>optional int64 activity_start_time = 1;</code>
     *
     * <pre>
     *上次关服时活动开启时间
     * </pre>
     */
    public boolean hasActivityStartTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 activity_start_time = 1;</code>
     *
     * <pre>
     *上次关服时活动开启时间
     * </pre>
     */
    public long getActivityStartTime() {
      return activityStartTime_;
    }

    public static final int GUILD_FIELD_NUMBER = 2;
    private java.util.List<app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto> guild_;
    /**
     * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
     */
    public java.util.List<app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto> getGuildList() {
      return guild_;
    }
    /**
     * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
     */
    public java.util.List<? extends app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProtoOrBuilder> 
        getGuildOrBuilderList() {
      return guild_;
    }
    /**
     * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
     */
    public int getGuildCount() {
      return guild_.size();
    }
    /**
     * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
     */
    public app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto getGuild(int index) {
      return guild_.get(index);
    }
    /**
     * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
     */
    public app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProtoOrBuilder getGuildOrBuilder(
        int index) {
      return guild_.get(index);
    }

    private void initFields() {
      activityStartTime_ = 0L;
      guild_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, activityStartTime_);
      }
      for (int i = 0; i < guild_.size(); i++) {
        output.writeMessage(2, guild_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, activityStartTime_);
      }
      for (int i = 0; i < guild_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, guild_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.GuildSingleExamInfoProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.GuildSingleExamInfoProto)
        app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return app.protobuf.server.GuildExamServerContent.internal_static_proto_GuildSingleExamInfoProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return app.protobuf.server.GuildExamServerContent.internal_static_proto_GuildSingleExamInfoProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.class, app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.Builder.class);
      }

      // Construct using app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGuildFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        activityStartTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (guildBuilder_ == null) {
          guild_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          guildBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return app.protobuf.server.GuildExamServerContent.internal_static_proto_GuildSingleExamInfoProto_descriptor;
      }

      public app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto getDefaultInstanceForType() {
        return app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.getDefaultInstance();
      }

      public app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto build() {
        app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto buildPartial() {
        app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto result = new app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.activityStartTime_ = activityStartTime_;
        if (guildBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            guild_ = java.util.Collections.unmodifiableList(guild_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.guild_ = guild_;
        } else {
          result.guild_ = guildBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto) {
          return mergeFrom((app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto other) {
        if (other == app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.getDefaultInstance()) return this;
        if (other.hasActivityStartTime()) {
          setActivityStartTime(other.getActivityStartTime());
        }
        if (guildBuilder_ == null) {
          if (!other.guild_.isEmpty()) {
            if (guild_.isEmpty()) {
              guild_ = other.guild_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureGuildIsMutable();
              guild_.addAll(other.guild_);
            }
            onChanged();
          }
        } else {
          if (!other.guild_.isEmpty()) {
            if (guildBuilder_.isEmpty()) {
              guildBuilder_.dispose();
              guildBuilder_ = null;
              guild_ = other.guild_;
              bitField0_ = (bitField0_ & ~0x00000002);
              guildBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGuildFieldBuilder() : null;
            } else {
              guildBuilder_.addAllMessages(other.guild_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long activityStartTime_ ;
      /**
       * <code>optional int64 activity_start_time = 1;</code>
       *
       * <pre>
       *上次关服时活动开启时间
       * </pre>
       */
      public boolean hasActivityStartTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 activity_start_time = 1;</code>
       *
       * <pre>
       *上次关服时活动开启时间
       * </pre>
       */
      public long getActivityStartTime() {
        return activityStartTime_;
      }
      /**
       * <code>optional int64 activity_start_time = 1;</code>
       *
       * <pre>
       *上次关服时活动开启时间
       * </pre>
       */
      public Builder setActivityStartTime(long value) {
        bitField0_ |= 0x00000001;
        activityStartTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 activity_start_time = 1;</code>
       *
       * <pre>
       *上次关服时活动开启时间
       * </pre>
       */
      public Builder clearActivityStartTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        activityStartTime_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto> guild_ =
        java.util.Collections.emptyList();
      private void ensureGuildIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          guild_ = new java.util.ArrayList<app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto>(guild_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto, app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.Builder, app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProtoOrBuilder> guildBuilder_;

      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public java.util.List<app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto> getGuildList() {
        if (guildBuilder_ == null) {
          return java.util.Collections.unmodifiableList(guild_);
        } else {
          return guildBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public int getGuildCount() {
        if (guildBuilder_ == null) {
          return guild_.size();
        } else {
          return guildBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto getGuild(int index) {
        if (guildBuilder_ == null) {
          return guild_.get(index);
        } else {
          return guildBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public Builder setGuild(
          int index, app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto value) {
        if (guildBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGuildIsMutable();
          guild_.set(index, value);
          onChanged();
        } else {
          guildBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public Builder setGuild(
          int index, app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.Builder builderForValue) {
        if (guildBuilder_ == null) {
          ensureGuildIsMutable();
          guild_.set(index, builderForValue.build());
          onChanged();
        } else {
          guildBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public Builder addGuild(app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto value) {
        if (guildBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGuildIsMutable();
          guild_.add(value);
          onChanged();
        } else {
          guildBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public Builder addGuild(
          int index, app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto value) {
        if (guildBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGuildIsMutable();
          guild_.add(index, value);
          onChanged();
        } else {
          guildBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public Builder addGuild(
          app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.Builder builderForValue) {
        if (guildBuilder_ == null) {
          ensureGuildIsMutable();
          guild_.add(builderForValue.build());
          onChanged();
        } else {
          guildBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public Builder addGuild(
          int index, app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.Builder builderForValue) {
        if (guildBuilder_ == null) {
          ensureGuildIsMutable();
          guild_.add(index, builderForValue.build());
          onChanged();
        } else {
          guildBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public Builder addAllGuild(
          java.lang.Iterable<? extends app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto> values) {
        if (guildBuilder_ == null) {
          ensureGuildIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, guild_);
          onChanged();
        } else {
          guildBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public Builder clearGuild() {
        if (guildBuilder_ == null) {
          guild_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          guildBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public Builder removeGuild(int index) {
        if (guildBuilder_ == null) {
          ensureGuildIsMutable();
          guild_.remove(index);
          onChanged();
        } else {
          guildBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.Builder getGuildBuilder(
          int index) {
        return getGuildFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProtoOrBuilder getGuildOrBuilder(
          int index) {
        if (guildBuilder_ == null) {
          return guild_.get(index);  } else {
          return guildBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public java.util.List<? extends app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProtoOrBuilder> 
           getGuildOrBuilderList() {
        if (guildBuilder_ != null) {
          return guildBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(guild_);
        }
      }
      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.Builder addGuildBuilder() {
        return getGuildFieldBuilder().addBuilder(
            app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.Builder addGuildBuilder(
          int index) {
        return getGuildFieldBuilder().addBuilder(
            index, app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.GuildSingleExamInfoProto.RankGuildExamInfoProto guild = 2;</code>
       */
      public java.util.List<app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.Builder> 
           getGuildBuilderList() {
        return getGuildFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto, app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.Builder, app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProtoOrBuilder> 
          getGuildFieldBuilder() {
        if (guildBuilder_ == null) {
          guildBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto, app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProto.Builder, app.protobuf.server.GuildExamServerContent.GuildSingleExamInfoProto.RankGuildExamInfoProtoOrBuilder>(
                  guild_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          guild_ = null;
        }
        return guildBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.GuildSingleExamInfoProto)
    }

    static {
      defaultInstance = new GuildSingleExamInfoProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.GuildSingleExamInfoProto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GuildExamModuleObjMinorProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_GuildExamModuleObjMinorProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GuildSingleExamInfoProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_GuildSingleExamInfoProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GuildSingleExamInfoProto_RankGuildExamInfoProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_GuildSingleExamInfoProto_RankGuildExamInfoProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036server/guild_exam_server.proto\022\005proto\"" +
      "\237\001\n\034GuildExamModuleObjMinorProto\022\037\n\027last" +
      "_join_activity_time\030\001 \001(\003\022\034\n\024guild_exam_" +
      "scene_exp\030\002 \001(\003\022%\n\035guild_exam_scene_cont" +
      "ribution\030\003 \001(\003\022\031\n\021last_collect_time\030\004 \001(" +
      "\003\"\321\001\n\030GuildSingleExamInfoProto\022\033\n\023activi" +
      "ty_start_time\030\001 \001(\003\022E\n\005guild\030\002 \003(\01326.pro" +
      "to.GuildSingleExamInfoProto.RankGuildExa" +
      "mInfoProto\032Q\n\026RankGuildExamInfoProto\022\017\n\007" +
      "guildId\030\001 \001(\003\022\r\n\005score\030\003 \001(\005\022\027\n\017scoreUpd",
      "ateTime\030\004 \001(\003B/\n\023app.protobuf.serverB\026Gu" +
      "ildExamServerContentH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_GuildExamModuleObjMinorProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_GuildExamModuleObjMinorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_GuildExamModuleObjMinorProto_descriptor,
        new java.lang.String[] { "LastJoinActivityTime", "GuildExamSceneExp", "GuildExamSceneContribution", "LastCollectTime", });
    internal_static_proto_GuildSingleExamInfoProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_GuildSingleExamInfoProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_GuildSingleExamInfoProto_descriptor,
        new java.lang.String[] { "ActivityStartTime", "Guild", });
    internal_static_proto_GuildSingleExamInfoProto_RankGuildExamInfoProto_descriptor =
      internal_static_proto_GuildSingleExamInfoProto_descriptor.getNestedTypes().get(0);
    internal_static_proto_GuildSingleExamInfoProto_RankGuildExamInfoProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_GuildSingleExamInfoProto_RankGuildExamInfoProto_descriptor,
        new java.lang.String[] { "GuildId", "Score", "ScoreUpdateTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
