// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/sprite_server.proto

package app.protobuf.server;

public final class SpriteServerContent {
  private SpriteServerContent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SpriteModuleObjMinorProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.SpriteModuleObjMinorProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.GoodsServerProto goods = 1;</code>
     */
    java.util.List<app.protobuf.server.GoodsServerContent.GoodsServerProto> 
        getGoodsList();
    /**
     * <code>repeated .proto.GoodsServerProto goods = 1;</code>
     */
    app.protobuf.server.GoodsServerContent.GoodsServerProto getGoods(int index);
    /**
     * <code>repeated .proto.GoodsServerProto goods = 1;</code>
     */
    int getGoodsCount();
    /**
     * <code>repeated .proto.GoodsServerProto goods = 1;</code>
     */
    java.util.List<? extends app.protobuf.server.GoodsServerContent.GoodsServerProtoOrBuilder> 
        getGoodsOrBuilderList();
    /**
     * <code>repeated .proto.GoodsServerProto goods = 1;</code>
     */
    app.protobuf.server.GoodsServerContent.GoodsServerProtoOrBuilder getGoodsOrBuilder(
        int index);

    /**
     * <code>optional int64 cache_sprite_addition_exp = 2;</code>
     *
     * <pre>
     *没有购买小鬼怪时，在经验副本中缓存的经验
     * </pre>
     */
    boolean hasCacheSpriteAdditionExp();
    /**
     * <code>optional int64 cache_sprite_addition_exp = 2;</code>
     *
     * <pre>
     *没有购买小鬼怪时，在经验副本中缓存的经验
     * </pre>
     */
    long getCacheSpriteAdditionExp();

    /**
     * <code>optional bool is_brought_sprite_goods = 3;</code>
     *
     * <pre>
     *是否购买过小鬼怪
     * </pre>
     */
    boolean hasIsBroughtSpriteGoods();
    /**
     * <code>optional bool is_brought_sprite_goods = 3;</code>
     *
     * <pre>
     *是否购买过小鬼怪
     * </pre>
     */
    boolean getIsBroughtSpriteGoods();
  }
  /**
   * Protobuf type {@code proto.SpriteModuleObjMinorProto}
   */
  public static final class SpriteModuleObjMinorProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.SpriteModuleObjMinorProto)
      SpriteModuleObjMinorProtoOrBuilder {
    // Use SpriteModuleObjMinorProto.newBuilder() to construct.
    private SpriteModuleObjMinorProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SpriteModuleObjMinorProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SpriteModuleObjMinorProto defaultInstance;
    public static SpriteModuleObjMinorProto getDefaultInstance() {
      return defaultInstance;
    }

    public SpriteModuleObjMinorProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SpriteModuleObjMinorProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                goods_ = new java.util.ArrayList<app.protobuf.server.GoodsServerContent.GoodsServerProto>();
                mutable_bitField0_ |= 0x00000001;
              }
              goods_.add(input.readMessage(app.protobuf.server.GoodsServerContent.GoodsServerProto.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              cacheSpriteAdditionExp_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              isBroughtSpriteGoods_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          goods_ = java.util.Collections.unmodifiableList(goods_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return app.protobuf.server.SpriteServerContent.internal_static_proto_SpriteModuleObjMinorProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return app.protobuf.server.SpriteServerContent.internal_static_proto_SpriteModuleObjMinorProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto.class, app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto.Builder.class);
    }

    public static com.google.protobuf.Parser<SpriteModuleObjMinorProto> PARSER =
        new com.google.protobuf.AbstractParser<SpriteModuleObjMinorProto>() {
      public SpriteModuleObjMinorProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SpriteModuleObjMinorProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SpriteModuleObjMinorProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int GOODS_FIELD_NUMBER = 1;
    private java.util.List<app.protobuf.server.GoodsServerContent.GoodsServerProto> goods_;
    /**
     * <code>repeated .proto.GoodsServerProto goods = 1;</code>
     */
    public java.util.List<app.protobuf.server.GoodsServerContent.GoodsServerProto> getGoodsList() {
      return goods_;
    }
    /**
     * <code>repeated .proto.GoodsServerProto goods = 1;</code>
     */
    public java.util.List<? extends app.protobuf.server.GoodsServerContent.GoodsServerProtoOrBuilder> 
        getGoodsOrBuilderList() {
      return goods_;
    }
    /**
     * <code>repeated .proto.GoodsServerProto goods = 1;</code>
     */
    public int getGoodsCount() {
      return goods_.size();
    }
    /**
     * <code>repeated .proto.GoodsServerProto goods = 1;</code>
     */
    public app.protobuf.server.GoodsServerContent.GoodsServerProto getGoods(int index) {
      return goods_.get(index);
    }
    /**
     * <code>repeated .proto.GoodsServerProto goods = 1;</code>
     */
    public app.protobuf.server.GoodsServerContent.GoodsServerProtoOrBuilder getGoodsOrBuilder(
        int index) {
      return goods_.get(index);
    }

    public static final int CACHE_SPRITE_ADDITION_EXP_FIELD_NUMBER = 2;
    private long cacheSpriteAdditionExp_;
    /**
     * <code>optional int64 cache_sprite_addition_exp = 2;</code>
     *
     * <pre>
     *没有购买小鬼怪时，在经验副本中缓存的经验
     * </pre>
     */
    public boolean hasCacheSpriteAdditionExp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 cache_sprite_addition_exp = 2;</code>
     *
     * <pre>
     *没有购买小鬼怪时，在经验副本中缓存的经验
     * </pre>
     */
    public long getCacheSpriteAdditionExp() {
      return cacheSpriteAdditionExp_;
    }

    public static final int IS_BROUGHT_SPRITE_GOODS_FIELD_NUMBER = 3;
    private boolean isBroughtSpriteGoods_;
    /**
     * <code>optional bool is_brought_sprite_goods = 3;</code>
     *
     * <pre>
     *是否购买过小鬼怪
     * </pre>
     */
    public boolean hasIsBroughtSpriteGoods() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool is_brought_sprite_goods = 3;</code>
     *
     * <pre>
     *是否购买过小鬼怪
     * </pre>
     */
    public boolean getIsBroughtSpriteGoods() {
      return isBroughtSpriteGoods_;
    }

    private void initFields() {
      goods_ = java.util.Collections.emptyList();
      cacheSpriteAdditionExp_ = 0L;
      isBroughtSpriteGoods_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < goods_.size(); i++) {
        output.writeMessage(1, goods_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(2, cacheSpriteAdditionExp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(3, isBroughtSpriteGoods_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < goods_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, goods_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, cacheSpriteAdditionExp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isBroughtSpriteGoods_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.SpriteModuleObjMinorProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.SpriteModuleObjMinorProto)
        app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return app.protobuf.server.SpriteServerContent.internal_static_proto_SpriteModuleObjMinorProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return app.protobuf.server.SpriteServerContent.internal_static_proto_SpriteModuleObjMinorProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto.class, app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto.Builder.class);
      }

      // Construct using app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGoodsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (goodsBuilder_ == null) {
          goods_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          goodsBuilder_.clear();
        }
        cacheSpriteAdditionExp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        isBroughtSpriteGoods_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return app.protobuf.server.SpriteServerContent.internal_static_proto_SpriteModuleObjMinorProto_descriptor;
      }

      public app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto getDefaultInstanceForType() {
        return app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto.getDefaultInstance();
      }

      public app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto build() {
        app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto buildPartial() {
        app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto result = new app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (goodsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            goods_ = java.util.Collections.unmodifiableList(goods_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.goods_ = goods_;
        } else {
          result.goods_ = goodsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cacheSpriteAdditionExp_ = cacheSpriteAdditionExp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isBroughtSpriteGoods_ = isBroughtSpriteGoods_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto) {
          return mergeFrom((app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto other) {
        if (other == app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto.getDefaultInstance()) return this;
        if (goodsBuilder_ == null) {
          if (!other.goods_.isEmpty()) {
            if (goods_.isEmpty()) {
              goods_ = other.goods_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGoodsIsMutable();
              goods_.addAll(other.goods_);
            }
            onChanged();
          }
        } else {
          if (!other.goods_.isEmpty()) {
            if (goodsBuilder_.isEmpty()) {
              goodsBuilder_.dispose();
              goodsBuilder_ = null;
              goods_ = other.goods_;
              bitField0_ = (bitField0_ & ~0x00000001);
              goodsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGoodsFieldBuilder() : null;
            } else {
              goodsBuilder_.addAllMessages(other.goods_);
            }
          }
        }
        if (other.hasCacheSpriteAdditionExp()) {
          setCacheSpriteAdditionExp(other.getCacheSpriteAdditionExp());
        }
        if (other.hasIsBroughtSpriteGoods()) {
          setIsBroughtSpriteGoods(other.getIsBroughtSpriteGoods());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (app.protobuf.server.SpriteServerContent.SpriteModuleObjMinorProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<app.protobuf.server.GoodsServerContent.GoodsServerProto> goods_ =
        java.util.Collections.emptyList();
      private void ensureGoodsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          goods_ = new java.util.ArrayList<app.protobuf.server.GoodsServerContent.GoodsServerProto>(goods_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          app.protobuf.server.GoodsServerContent.GoodsServerProto, app.protobuf.server.GoodsServerContent.GoodsServerProto.Builder, app.protobuf.server.GoodsServerContent.GoodsServerProtoOrBuilder> goodsBuilder_;

      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public java.util.List<app.protobuf.server.GoodsServerContent.GoodsServerProto> getGoodsList() {
        if (goodsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(goods_);
        } else {
          return goodsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public int getGoodsCount() {
        if (goodsBuilder_ == null) {
          return goods_.size();
        } else {
          return goodsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public app.protobuf.server.GoodsServerContent.GoodsServerProto getGoods(int index) {
        if (goodsBuilder_ == null) {
          return goods_.get(index);
        } else {
          return goodsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public Builder setGoods(
          int index, app.protobuf.server.GoodsServerContent.GoodsServerProto value) {
        if (goodsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGoodsIsMutable();
          goods_.set(index, value);
          onChanged();
        } else {
          goodsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public Builder setGoods(
          int index, app.protobuf.server.GoodsServerContent.GoodsServerProto.Builder builderForValue) {
        if (goodsBuilder_ == null) {
          ensureGoodsIsMutable();
          goods_.set(index, builderForValue.build());
          onChanged();
        } else {
          goodsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public Builder addGoods(app.protobuf.server.GoodsServerContent.GoodsServerProto value) {
        if (goodsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGoodsIsMutable();
          goods_.add(value);
          onChanged();
        } else {
          goodsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public Builder addGoods(
          int index, app.protobuf.server.GoodsServerContent.GoodsServerProto value) {
        if (goodsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGoodsIsMutable();
          goods_.add(index, value);
          onChanged();
        } else {
          goodsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public Builder addGoods(
          app.protobuf.server.GoodsServerContent.GoodsServerProto.Builder builderForValue) {
        if (goodsBuilder_ == null) {
          ensureGoodsIsMutable();
          goods_.add(builderForValue.build());
          onChanged();
        } else {
          goodsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public Builder addGoods(
          int index, app.protobuf.server.GoodsServerContent.GoodsServerProto.Builder builderForValue) {
        if (goodsBuilder_ == null) {
          ensureGoodsIsMutable();
          goods_.add(index, builderForValue.build());
          onChanged();
        } else {
          goodsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public Builder addAllGoods(
          java.lang.Iterable<? extends app.protobuf.server.GoodsServerContent.GoodsServerProto> values) {
        if (goodsBuilder_ == null) {
          ensureGoodsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, goods_);
          onChanged();
        } else {
          goodsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public Builder clearGoods() {
        if (goodsBuilder_ == null) {
          goods_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          goodsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public Builder removeGoods(int index) {
        if (goodsBuilder_ == null) {
          ensureGoodsIsMutable();
          goods_.remove(index);
          onChanged();
        } else {
          goodsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public app.protobuf.server.GoodsServerContent.GoodsServerProto.Builder getGoodsBuilder(
          int index) {
        return getGoodsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public app.protobuf.server.GoodsServerContent.GoodsServerProtoOrBuilder getGoodsOrBuilder(
          int index) {
        if (goodsBuilder_ == null) {
          return goods_.get(index);  } else {
          return goodsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public java.util.List<? extends app.protobuf.server.GoodsServerContent.GoodsServerProtoOrBuilder> 
           getGoodsOrBuilderList() {
        if (goodsBuilder_ != null) {
          return goodsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(goods_);
        }
      }
      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public app.protobuf.server.GoodsServerContent.GoodsServerProto.Builder addGoodsBuilder() {
        return getGoodsFieldBuilder().addBuilder(
            app.protobuf.server.GoodsServerContent.GoodsServerProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public app.protobuf.server.GoodsServerContent.GoodsServerProto.Builder addGoodsBuilder(
          int index) {
        return getGoodsFieldBuilder().addBuilder(
            index, app.protobuf.server.GoodsServerContent.GoodsServerProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.GoodsServerProto goods = 1;</code>
       */
      public java.util.List<app.protobuf.server.GoodsServerContent.GoodsServerProto.Builder> 
           getGoodsBuilderList() {
        return getGoodsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          app.protobuf.server.GoodsServerContent.GoodsServerProto, app.protobuf.server.GoodsServerContent.GoodsServerProto.Builder, app.protobuf.server.GoodsServerContent.GoodsServerProtoOrBuilder> 
          getGoodsFieldBuilder() {
        if (goodsBuilder_ == null) {
          goodsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              app.protobuf.server.GoodsServerContent.GoodsServerProto, app.protobuf.server.GoodsServerContent.GoodsServerProto.Builder, app.protobuf.server.GoodsServerContent.GoodsServerProtoOrBuilder>(
                  goods_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          goods_ = null;
        }
        return goodsBuilder_;
      }

      private long cacheSpriteAdditionExp_ ;
      /**
       * <code>optional int64 cache_sprite_addition_exp = 2;</code>
       *
       * <pre>
       *没有购买小鬼怪时，在经验副本中缓存的经验
       * </pre>
       */
      public boolean hasCacheSpriteAdditionExp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 cache_sprite_addition_exp = 2;</code>
       *
       * <pre>
       *没有购买小鬼怪时，在经验副本中缓存的经验
       * </pre>
       */
      public long getCacheSpriteAdditionExp() {
        return cacheSpriteAdditionExp_;
      }
      /**
       * <code>optional int64 cache_sprite_addition_exp = 2;</code>
       *
       * <pre>
       *没有购买小鬼怪时，在经验副本中缓存的经验
       * </pre>
       */
      public Builder setCacheSpriteAdditionExp(long value) {
        bitField0_ |= 0x00000002;
        cacheSpriteAdditionExp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cache_sprite_addition_exp = 2;</code>
       *
       * <pre>
       *没有购买小鬼怪时，在经验副本中缓存的经验
       * </pre>
       */
      public Builder clearCacheSpriteAdditionExp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cacheSpriteAdditionExp_ = 0L;
        onChanged();
        return this;
      }

      private boolean isBroughtSpriteGoods_ ;
      /**
       * <code>optional bool is_brought_sprite_goods = 3;</code>
       *
       * <pre>
       *是否购买过小鬼怪
       * </pre>
       */
      public boolean hasIsBroughtSpriteGoods() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool is_brought_sprite_goods = 3;</code>
       *
       * <pre>
       *是否购买过小鬼怪
       * </pre>
       */
      public boolean getIsBroughtSpriteGoods() {
        return isBroughtSpriteGoods_;
      }
      /**
       * <code>optional bool is_brought_sprite_goods = 3;</code>
       *
       * <pre>
       *是否购买过小鬼怪
       * </pre>
       */
      public Builder setIsBroughtSpriteGoods(boolean value) {
        bitField0_ |= 0x00000004;
        isBroughtSpriteGoods_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_brought_sprite_goods = 3;</code>
       *
       * <pre>
       *是否购买过小鬼怪
       * </pre>
       */
      public Builder clearIsBroughtSpriteGoods() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isBroughtSpriteGoods_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.SpriteModuleObjMinorProto)
    }

    static {
      defaultInstance = new SpriteModuleObjMinorProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.SpriteModuleObjMinorProto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SpriteModuleObjMinorProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_SpriteModuleObjMinorProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032server/sprite_server.proto\022\005proto\032\031ser" +
      "ver/goods_server.proto\"\207\001\n\031SpriteModuleO" +
      "bjMinorProto\022&\n\005goods\030\001 \003(\0132\027.proto.Good" +
      "sServerProto\022!\n\031cache_sprite_addition_ex" +
      "p\030\002 \001(\003\022\037\n\027is_brought_sprite_goods\030\003 \001(\010" +
      "B,\n\023app.protobuf.serverB\023SpriteServerCon" +
      "tentH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          app.protobuf.server.GoodsServerContent.getDescriptor(),
        }, assigner);
    internal_static_proto_SpriteModuleObjMinorProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_SpriteModuleObjMinorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_SpriteModuleObjMinorProto_descriptor,
        new java.lang.String[] { "Goods", "CacheSpriteAdditionExp", "IsBroughtSpriteGoods", });
    app.protobuf.server.GoodsServerContent.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
