// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/pet_plugin_server.proto

package app.protobuf.server;

public final class PetPluginServerContent {
  private PetPluginServerContent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PetPluginModuleObjServerProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PetPluginModuleObjServerProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
     */
    java.util.List<app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto> 
        getActivateObjList();
    /**
     * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
     */
    app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto getActivateObj(int index);
    /**
     * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
     */
    int getActivateObjCount();
    /**
     * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
     */
    java.util.List<? extends app.protobuf.server.PetPluginServerContent.PetPluginObjServerProtoOrBuilder> 
        getActivateObjOrBuilderList();
    /**
     * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
     */
    app.protobuf.server.PetPluginServerContent.PetPluginObjServerProtoOrBuilder getActivateObjOrBuilder(
        int index);

    /**
     * <code>optional int64 upStageMaterial = 2;</code>
     *
     * <pre>
     *升阶材料
     * </pre>
     */
    boolean hasUpStageMaterial();
    /**
     * <code>optional int64 upStageMaterial = 2;</code>
     *
     * <pre>
     *升阶材料
     * </pre>
     */
    long getUpStageMaterial();

    /**
     * <code>optional int32 use_plugin_id = 3;</code>
     *
     * <pre>
     *当前使用的插件ID
     * </pre>
     */
    boolean hasUsePluginId();
    /**
     * <code>optional int32 use_plugin_id = 3;</code>
     *
     * <pre>
     *当前使用的插件ID
     * </pre>
     */
    int getUsePluginId();

    /**
     * <code>optional bool isHide = 4;</code>
     *
     * <pre>
     *是否隐藏
     * </pre>
     */
    boolean hasIsHide();
    /**
     * <code>optional bool isHide = 4;</code>
     *
     * <pre>
     *是否隐藏
     * </pre>
     */
    boolean getIsHide();
  }
  /**
   * Protobuf type {@code proto.PetPluginModuleObjServerProto}
   *
   * <pre>
   *宠物插件
   * </pre>
   */
  public static final class PetPluginModuleObjServerProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.PetPluginModuleObjServerProto)
      PetPluginModuleObjServerProtoOrBuilder {
    // Use PetPluginModuleObjServerProto.newBuilder() to construct.
    private PetPluginModuleObjServerProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PetPluginModuleObjServerProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PetPluginModuleObjServerProto defaultInstance;
    public static PetPluginModuleObjServerProto getDefaultInstance() {
      return defaultInstance;
    }

    public PetPluginModuleObjServerProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PetPluginModuleObjServerProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                activateObj_ = new java.util.ArrayList<app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto>();
                mutable_bitField0_ |= 0x00000001;
              }
              activateObj_.add(input.readMessage(app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              upStageMaterial_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              usePluginId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              isHide_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          activateObj_ = java.util.Collections.unmodifiableList(activateObj_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return app.protobuf.server.PetPluginServerContent.internal_static_proto_PetPluginModuleObjServerProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return app.protobuf.server.PetPluginServerContent.internal_static_proto_PetPluginModuleObjServerProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto.class, app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto.Builder.class);
    }

    public static com.google.protobuf.Parser<PetPluginModuleObjServerProto> PARSER =
        new com.google.protobuf.AbstractParser<PetPluginModuleObjServerProto>() {
      public PetPluginModuleObjServerProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PetPluginModuleObjServerProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PetPluginModuleObjServerProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ACTIVATEOBJ_FIELD_NUMBER = 1;
    private java.util.List<app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto> activateObj_;
    /**
     * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
     */
    public java.util.List<app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto> getActivateObjList() {
      return activateObj_;
    }
    /**
     * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
     */
    public java.util.List<? extends app.protobuf.server.PetPluginServerContent.PetPluginObjServerProtoOrBuilder> 
        getActivateObjOrBuilderList() {
      return activateObj_;
    }
    /**
     * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
     */
    public int getActivateObjCount() {
      return activateObj_.size();
    }
    /**
     * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
     */
    public app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto getActivateObj(int index) {
      return activateObj_.get(index);
    }
    /**
     * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
     */
    public app.protobuf.server.PetPluginServerContent.PetPluginObjServerProtoOrBuilder getActivateObjOrBuilder(
        int index) {
      return activateObj_.get(index);
    }

    public static final int UPSTAGEMATERIAL_FIELD_NUMBER = 2;
    private long upStageMaterial_;
    /**
     * <code>optional int64 upStageMaterial = 2;</code>
     *
     * <pre>
     *升阶材料
     * </pre>
     */
    public boolean hasUpStageMaterial() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 upStageMaterial = 2;</code>
     *
     * <pre>
     *升阶材料
     * </pre>
     */
    public long getUpStageMaterial() {
      return upStageMaterial_;
    }

    public static final int USE_PLUGIN_ID_FIELD_NUMBER = 3;
    private int usePluginId_;
    /**
     * <code>optional int32 use_plugin_id = 3;</code>
     *
     * <pre>
     *当前使用的插件ID
     * </pre>
     */
    public boolean hasUsePluginId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 use_plugin_id = 3;</code>
     *
     * <pre>
     *当前使用的插件ID
     * </pre>
     */
    public int getUsePluginId() {
      return usePluginId_;
    }

    public static final int ISHIDE_FIELD_NUMBER = 4;
    private boolean isHide_;
    /**
     * <code>optional bool isHide = 4;</code>
     *
     * <pre>
     *是否隐藏
     * </pre>
     */
    public boolean hasIsHide() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool isHide = 4;</code>
     *
     * <pre>
     *是否隐藏
     * </pre>
     */
    public boolean getIsHide() {
      return isHide_;
    }

    private void initFields() {
      activateObj_ = java.util.Collections.emptyList();
      upStageMaterial_ = 0L;
      usePluginId_ = 0;
      isHide_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < activateObj_.size(); i++) {
        output.writeMessage(1, activateObj_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(2, upStageMaterial_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, usePluginId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(4, isHide_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < activateObj_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, activateObj_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, upStageMaterial_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, usePluginId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isHide_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PetPluginModuleObjServerProto}
     *
     * <pre>
     *宠物插件
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PetPluginModuleObjServerProto)
        app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return app.protobuf.server.PetPluginServerContent.internal_static_proto_PetPluginModuleObjServerProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return app.protobuf.server.PetPluginServerContent.internal_static_proto_PetPluginModuleObjServerProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto.class, app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto.Builder.class);
      }

      // Construct using app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getActivateObjFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (activateObjBuilder_ == null) {
          activateObj_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          activateObjBuilder_.clear();
        }
        upStageMaterial_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        usePluginId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        isHide_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return app.protobuf.server.PetPluginServerContent.internal_static_proto_PetPluginModuleObjServerProto_descriptor;
      }

      public app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto getDefaultInstanceForType() {
        return app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto.getDefaultInstance();
      }

      public app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto build() {
        app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto buildPartial() {
        app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto result = new app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (activateObjBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            activateObj_ = java.util.Collections.unmodifiableList(activateObj_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.activateObj_ = activateObj_;
        } else {
          result.activateObj_ = activateObjBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.upStageMaterial_ = upStageMaterial_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.usePluginId_ = usePluginId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isHide_ = isHide_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto) {
          return mergeFrom((app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto other) {
        if (other == app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto.getDefaultInstance()) return this;
        if (activateObjBuilder_ == null) {
          if (!other.activateObj_.isEmpty()) {
            if (activateObj_.isEmpty()) {
              activateObj_ = other.activateObj_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureActivateObjIsMutable();
              activateObj_.addAll(other.activateObj_);
            }
            onChanged();
          }
        } else {
          if (!other.activateObj_.isEmpty()) {
            if (activateObjBuilder_.isEmpty()) {
              activateObjBuilder_.dispose();
              activateObjBuilder_ = null;
              activateObj_ = other.activateObj_;
              bitField0_ = (bitField0_ & ~0x00000001);
              activateObjBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getActivateObjFieldBuilder() : null;
            } else {
              activateObjBuilder_.addAllMessages(other.activateObj_);
            }
          }
        }
        if (other.hasUpStageMaterial()) {
          setUpStageMaterial(other.getUpStageMaterial());
        }
        if (other.hasUsePluginId()) {
          setUsePluginId(other.getUsePluginId());
        }
        if (other.hasIsHide()) {
          setIsHide(other.getIsHide());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (app.protobuf.server.PetPluginServerContent.PetPluginModuleObjServerProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto> activateObj_ =
        java.util.Collections.emptyList();
      private void ensureActivateObjIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          activateObj_ = new java.util.ArrayList<app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto>(activateObj_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto, app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.Builder, app.protobuf.server.PetPluginServerContent.PetPluginObjServerProtoOrBuilder> activateObjBuilder_;

      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public java.util.List<app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto> getActivateObjList() {
        if (activateObjBuilder_ == null) {
          return java.util.Collections.unmodifiableList(activateObj_);
        } else {
          return activateObjBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public int getActivateObjCount() {
        if (activateObjBuilder_ == null) {
          return activateObj_.size();
        } else {
          return activateObjBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto getActivateObj(int index) {
        if (activateObjBuilder_ == null) {
          return activateObj_.get(index);
        } else {
          return activateObjBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public Builder setActivateObj(
          int index, app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto value) {
        if (activateObjBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActivateObjIsMutable();
          activateObj_.set(index, value);
          onChanged();
        } else {
          activateObjBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public Builder setActivateObj(
          int index, app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.Builder builderForValue) {
        if (activateObjBuilder_ == null) {
          ensureActivateObjIsMutable();
          activateObj_.set(index, builderForValue.build());
          onChanged();
        } else {
          activateObjBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public Builder addActivateObj(app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto value) {
        if (activateObjBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActivateObjIsMutable();
          activateObj_.add(value);
          onChanged();
        } else {
          activateObjBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public Builder addActivateObj(
          int index, app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto value) {
        if (activateObjBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActivateObjIsMutable();
          activateObj_.add(index, value);
          onChanged();
        } else {
          activateObjBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public Builder addActivateObj(
          app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.Builder builderForValue) {
        if (activateObjBuilder_ == null) {
          ensureActivateObjIsMutable();
          activateObj_.add(builderForValue.build());
          onChanged();
        } else {
          activateObjBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public Builder addActivateObj(
          int index, app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.Builder builderForValue) {
        if (activateObjBuilder_ == null) {
          ensureActivateObjIsMutable();
          activateObj_.add(index, builderForValue.build());
          onChanged();
        } else {
          activateObjBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public Builder addAllActivateObj(
          java.lang.Iterable<? extends app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto> values) {
        if (activateObjBuilder_ == null) {
          ensureActivateObjIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, activateObj_);
          onChanged();
        } else {
          activateObjBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public Builder clearActivateObj() {
        if (activateObjBuilder_ == null) {
          activateObj_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          activateObjBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public Builder removeActivateObj(int index) {
        if (activateObjBuilder_ == null) {
          ensureActivateObjIsMutable();
          activateObj_.remove(index);
          onChanged();
        } else {
          activateObjBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.Builder getActivateObjBuilder(
          int index) {
        return getActivateObjFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public app.protobuf.server.PetPluginServerContent.PetPluginObjServerProtoOrBuilder getActivateObjOrBuilder(
          int index) {
        if (activateObjBuilder_ == null) {
          return activateObj_.get(index);  } else {
          return activateObjBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public java.util.List<? extends app.protobuf.server.PetPluginServerContent.PetPluginObjServerProtoOrBuilder> 
           getActivateObjOrBuilderList() {
        if (activateObjBuilder_ != null) {
          return activateObjBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(activateObj_);
        }
      }
      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.Builder addActivateObjBuilder() {
        return getActivateObjFieldBuilder().addBuilder(
            app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.Builder addActivateObjBuilder(
          int index) {
        return getActivateObjFieldBuilder().addBuilder(
            index, app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.PetPluginObjServerProto activateObj = 1;</code>
       */
      public java.util.List<app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.Builder> 
           getActivateObjBuilderList() {
        return getActivateObjFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto, app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.Builder, app.protobuf.server.PetPluginServerContent.PetPluginObjServerProtoOrBuilder> 
          getActivateObjFieldBuilder() {
        if (activateObjBuilder_ == null) {
          activateObjBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto, app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.Builder, app.protobuf.server.PetPluginServerContent.PetPluginObjServerProtoOrBuilder>(
                  activateObj_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          activateObj_ = null;
        }
        return activateObjBuilder_;
      }

      private long upStageMaterial_ ;
      /**
       * <code>optional int64 upStageMaterial = 2;</code>
       *
       * <pre>
       *升阶材料
       * </pre>
       */
      public boolean hasUpStageMaterial() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 upStageMaterial = 2;</code>
       *
       * <pre>
       *升阶材料
       * </pre>
       */
      public long getUpStageMaterial() {
        return upStageMaterial_;
      }
      /**
       * <code>optional int64 upStageMaterial = 2;</code>
       *
       * <pre>
       *升阶材料
       * </pre>
       */
      public Builder setUpStageMaterial(long value) {
        bitField0_ |= 0x00000002;
        upStageMaterial_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 upStageMaterial = 2;</code>
       *
       * <pre>
       *升阶材料
       * </pre>
       */
      public Builder clearUpStageMaterial() {
        bitField0_ = (bitField0_ & ~0x00000002);
        upStageMaterial_ = 0L;
        onChanged();
        return this;
      }

      private int usePluginId_ ;
      /**
       * <code>optional int32 use_plugin_id = 3;</code>
       *
       * <pre>
       *当前使用的插件ID
       * </pre>
       */
      public boolean hasUsePluginId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 use_plugin_id = 3;</code>
       *
       * <pre>
       *当前使用的插件ID
       * </pre>
       */
      public int getUsePluginId() {
        return usePluginId_;
      }
      /**
       * <code>optional int32 use_plugin_id = 3;</code>
       *
       * <pre>
       *当前使用的插件ID
       * </pre>
       */
      public Builder setUsePluginId(int value) {
        bitField0_ |= 0x00000004;
        usePluginId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 use_plugin_id = 3;</code>
       *
       * <pre>
       *当前使用的插件ID
       * </pre>
       */
      public Builder clearUsePluginId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        usePluginId_ = 0;
        onChanged();
        return this;
      }

      private boolean isHide_ ;
      /**
       * <code>optional bool isHide = 4;</code>
       *
       * <pre>
       *是否隐藏
       * </pre>
       */
      public boolean hasIsHide() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool isHide = 4;</code>
       *
       * <pre>
       *是否隐藏
       * </pre>
       */
      public boolean getIsHide() {
        return isHide_;
      }
      /**
       * <code>optional bool isHide = 4;</code>
       *
       * <pre>
       *是否隐藏
       * </pre>
       */
      public Builder setIsHide(boolean value) {
        bitField0_ |= 0x00000008;
        isHide_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isHide = 4;</code>
       *
       * <pre>
       *是否隐藏
       * </pre>
       */
      public Builder clearIsHide() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isHide_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.PetPluginModuleObjServerProto)
    }

    static {
      defaultInstance = new PetPluginModuleObjServerProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.PetPluginModuleObjServerProto)
  }

  public interface PetPluginObjServerProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PetPluginObjServerProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional int32 stage = 2;</code>
     */
    boolean hasStage();
    /**
     * <code>optional int32 stage = 2;</code>
     */
    int getStage();
  }
  /**
   * Protobuf type {@code proto.PetPluginObjServerProto}
   */
  public static final class PetPluginObjServerProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.PetPluginObjServerProto)
      PetPluginObjServerProtoOrBuilder {
    // Use PetPluginObjServerProto.newBuilder() to construct.
    private PetPluginObjServerProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PetPluginObjServerProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PetPluginObjServerProto defaultInstance;
    public static PetPluginObjServerProto getDefaultInstance() {
      return defaultInstance;
    }

    public PetPluginObjServerProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PetPluginObjServerProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              stage_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return app.protobuf.server.PetPluginServerContent.internal_static_proto_PetPluginObjServerProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return app.protobuf.server.PetPluginServerContent.internal_static_proto_PetPluginObjServerProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.class, app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.Builder.class);
    }

    public static com.google.protobuf.Parser<PetPluginObjServerProto> PARSER =
        new com.google.protobuf.AbstractParser<PetPluginObjServerProto>() {
      public PetPluginObjServerProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PetPluginObjServerProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PetPluginObjServerProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int STAGE_FIELD_NUMBER = 2;
    private int stage_;
    /**
     * <code>optional int32 stage = 2;</code>
     */
    public boolean hasStage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 stage = 2;</code>
     */
    public int getStage() {
      return stage_;
    }

    private void initFields() {
      id_ = 0;
      stage_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, stage_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, stage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PetPluginObjServerProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PetPluginObjServerProto)
        app.protobuf.server.PetPluginServerContent.PetPluginObjServerProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return app.protobuf.server.PetPluginServerContent.internal_static_proto_PetPluginObjServerProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return app.protobuf.server.PetPluginServerContent.internal_static_proto_PetPluginObjServerProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.class, app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.Builder.class);
      }

      // Construct using app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        stage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return app.protobuf.server.PetPluginServerContent.internal_static_proto_PetPluginObjServerProto_descriptor;
      }

      public app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto getDefaultInstanceForType() {
        return app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.getDefaultInstance();
      }

      public app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto build() {
        app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto buildPartial() {
        app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto result = new app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.stage_ = stage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto) {
          return mergeFrom((app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto other) {
        if (other == app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasStage()) {
          setStage(other.getStage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (app.protobuf.server.PetPluginServerContent.PetPluginObjServerProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int stage_ ;
      /**
       * <code>optional int32 stage = 2;</code>
       */
      public boolean hasStage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 stage = 2;</code>
       */
      public int getStage() {
        return stage_;
      }
      /**
       * <code>optional int32 stage = 2;</code>
       */
      public Builder setStage(int value) {
        bitField0_ |= 0x00000002;
        stage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 stage = 2;</code>
       */
      public Builder clearStage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stage_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.PetPluginObjServerProto)
    }

    static {
      defaultInstance = new PetPluginObjServerProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.PetPluginObjServerProto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PetPluginModuleObjServerProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_PetPluginModuleObjServerProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PetPluginObjServerProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_PetPluginObjServerProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036server/pet_plugin_server.proto\022\005proto\"" +
      "\224\001\n\035PetPluginModuleObjServerProto\0223\n\013act" +
      "ivateObj\030\001 \003(\0132\036.proto.PetPluginObjServe" +
      "rProto\022\027\n\017upStageMaterial\030\002 \001(\003\022\025\n\ruse_p" +
      "lugin_id\030\003 \001(\005\022\016\n\006isHide\030\004 \001(\010\"4\n\027PetPlu" +
      "ginObjServerProto\022\n\n\002id\030\001 \001(\005\022\r\n\005stage\030\002" +
      " \001(\005B/\n\023app.protobuf.serverB\026PetPluginSe" +
      "rverContentH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_PetPluginModuleObjServerProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_PetPluginModuleObjServerProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_PetPluginModuleObjServerProto_descriptor,
        new java.lang.String[] { "ActivateObj", "UpStageMaterial", "UsePluginId", "IsHide", });
    internal_static_proto_PetPluginObjServerProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_PetPluginObjServerProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_PetPluginObjServerProto_descriptor,
        new java.lang.String[] { "Id", "Stage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
